<Workspace Version="0.9.1.4062" X="1156.86906082403" Y="685.178676209412" zoom="0.839369585477944" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="207b87ed-7a2c-4f02-84ee-0f2e6afb69db" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1252.20447149643" y="-225.940456767566" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.Creation import *
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import TaskDialog
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
pos = IN[0]
viewport = UnwrapElement(IN[1])


x1 = pos[0]
y1 = pos[1]
z1 = pos[2]

sheet = doc.GetElement(viewport.SheetId)
bdbox = viewport.get_BoundingBox(sheet)
positions= (bdbox.Max + bdbox.Min)/2
x2 = positions.X
y2 = positions.Y
z2 = positions.Z


#vpid = viewport.Id
#xyz = app.Create.NewXYZ(x1,y1,z1)
loc = viewport.Location
xyz = app.Create.NewXYZ(x1-x2,y1-y2,z1)

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)
try:
	#MoveElement(doc, vpid, xyz)
	newloc = loc.Move(xyz)
except:
	pass
 
# End Transaction
TransactionManager.Instance.TransactionTaskDone()
doc.Regenerate()

#Assign your output to the OUT variable.
OUT = newloc</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c7430537-4517-4345-9af3-9b2d8129b847" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CSV.ReadFromFile" x="797.313379639048" y="-157.436483182455" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="DSCoreNodes.dll" function="DSCore.IO.CSV.ReadFromFile@var" />
    <CoreNodeModels.Input.FileObject guid="cacbf366-0d15-4dba-8349-6fa340f87cf2" type="CoreNodeModels.Input.FileObject" nickname="File.FromPath" x="605.983741171923" y="-179.213840406355" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7056c012-81cd-4eca-ad89-11935b9a8d7f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="973.087762946244" y="-160.54753421444" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Nodes.DSModelElementSelection guid="72201fc3-5bda-4275-b652-79555f418cf2" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select viewport to Move" x="-1142.43106896197" y="-269.545904461394" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <instance id="9d48e2b7-59f9-4df4-9b7c-4e9042eccc50-000f5edb" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSModelElementSelection guid="51769cc2-68d4-4c53-ae28-9cac297223bc" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select viewport to get Location on sheet" x="-1162.10761191061" y="-593.324051869318" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <instance id="728d049f-51b3-47e0-8923-867ee360bc41-000ecc86" />
    </Dynamo.Nodes.DSModelElementSelection>
    <PythonNodeModels.PythonNode guid="4a409305-f61c-4ce4-8d56-f1e69286b4a1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="252.876304505701" y="-567.666306422625" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import ElementId
from Autodesk.Revit.DB import ViewSheet
from Autodesk.Revit.DB import Viewport
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import TaskDialog
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
viewport = UnwrapElement(IN[0])

sheet = doc.GetElement(viewport.SheetId)

bdbox = viewport.get_BoundingBox(sheet)

positions= (bdbox.Max + bdbox.Min)/2
#Assign your output to the OUT variable.
OUT = positions.X,positions.Y,positions.Z</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.Filename guid="5cdc0de4-b55c-4e9d-ac36-d2d07f31cac2" type="CoreNodeModels.Input.Filename" nickname="File Path" x="-1155.49856187318" y="-486.240984928785" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>R:\BimESC\01_PROJECTS\HAR-HOI AN PEARL\05-Wip\02-Model\DYN\xyz.csv</System.String>
    </CoreNodeModels.Input.Filename>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0e46284b-39c8-4ac1-9696-e1f1d0ce2283" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CSV.WriteToFile" x="577.26315383908" y="-547.047011412853" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="DSCoreNodes.dll" function="DSCore.IO.CSV.WriteToFile@string,var[][]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0855b0bd-9546-4960-bb5e-e26e3097cc72" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Transaction.Start" x="270.259255391529" y="-308.001448431123" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Transaction.Transaction.Start@var" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1f68d17c-21d4-4523-ad28-99a508641cf5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Transaction.End" x="1440.92605273733" y="-254.981424304223" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Transaction.Transaction.End@var" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="207b87ed-7a2c-4f02-84ee-0f2e6afb69db" start_index="0" end="1f68d17c-21d4-4523-ad28-99a508641cf5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c7430537-4517-4345-9af3-9b2d8129b847" start_index="0" end="7056c012-81cd-4eca-ad89-11935b9a8d7f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cacbf366-0d15-4dba-8349-6fa340f87cf2" start_index="0" end="c7430537-4517-4345-9af3-9b2d8129b847" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7056c012-81cd-4eca-ad89-11935b9a8d7f" start_index="0" end="207b87ed-7a2c-4f02-84ee-0f2e6afb69db" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="72201fc3-5bda-4275-b652-79555f418cf2" start_index="0" end="0855b0bd-9546-4960-bb5e-e26e3097cc72" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="51769cc2-68d4-4c53-ae28-9cac297223bc" start_index="0" end="4a409305-f61c-4ce4-8d56-f1e69286b4a1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a409305-f61c-4ce4-8d56-f1e69286b4a1" start_index="0" end="0e46284b-39c8-4ac1-9696-e1f1d0ce2283" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5cdc0de4-b55c-4e9d-ac36-d2d07f31cac2" start_index="0" end="0e46284b-39c8-4ac1-9696-e1f1d0ce2283" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5cdc0de4-b55c-4e9d-ac36-d2d07f31cac2" start_index="0" end="cacbf366-0d15-4dba-8349-6fa340f87cf2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0855b0bd-9546-4960-bb5e-e26e3097cc72" start_index="0" end="207b87ed-7a2c-4f02-84ee-0f2e6afb69db" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="1c92e31e-3ffe-4ff4-b840-cfc544cbba2e" text="1" x="-1262.37410715627" y="-569.300721107553" />
    <Dynamo.Graph.Notes.NoteModel guid="5afc9a5a-ffbc-4644-8af4-f09143818e84" text="2" x="-1259.02055919688" y="-314.299023003415" />
    <Dynamo.Graph.Notes.NoteModel guid="f4c5c18e-f6c3-42e8-9b6c-e7d739345af1" text="--&gt; Run --&gt;" x="-1264.94820677279" y="-520.473850094817" />
    <Dynamo.Graph.Notes.NoteModel guid="c3e32443-9e89-4f9c-9e2f-dc6cb3d2b342" text="Run" x="-1132.20977430475" y="-315.62051454643" />
    <Dynamo.Graph.Notes.NoteModel guid="bc2dd65f-2ac4-4ca1-ac5a-91bb8ed6b899" text="--&gt; Run" x="-1259.97385754439" y="-271.571061861397" />
    <Dynamo.Graph.Notes.NoteModel guid="2802a5c2-872e-4140-b4ff-ce460725fc04" text="Guide:&#xD;&#xA;## Only use for VIEWPORT, posible to Multi task&#xD;&#xA;## Process&#xD;&#xA;1 --&gt; Run  --&gt; 2 --&gt; Run" x="-1264.98768562385" y="-704.925072938195" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="7f369197-93b9-429b-9ac4-da2ff3aacf00" annotationText="&lt;Click here to edit the group title&gt;" left="260.259255391529" top="-338.001448431123" width="1329.6667973458" height="273.564965248668" fontSize="14" InitialTop="-308.001448431123" InitialHeight="273.564965248668" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="207b87ed-7a2c-4f02-84ee-0f2e6afb69db" />
      <Models ModelGuid="c7430537-4517-4345-9af3-9b2d8129b847" />
      <Models ModelGuid="cacbf366-0d15-4dba-8349-6fa340f87cf2" />
      <Models ModelGuid="7056c012-81cd-4eca-ad89-11935b9a8d7f" />
      <Models ModelGuid="0855b0bd-9546-4960-bb5e-e26e3097cc72" />
      <Models ModelGuid="1f68d17c-21d4-4523-ad28-99a508641cf5" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="474b75cf-5a9a-4705-abfe-1c13aedc861d" annotationText="&lt;Click here to edit the group title&gt;" left="242.876304505701" top="-597.666306422625" width="470.386849333379" height="169.619295009772" fontSize="14" InitialTop="-567.666306422625" InitialHeight="298.740908863067" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="4a409305-f61c-4ce4-8d56-f1e69286b4a1" />
      <Models ModelGuid="0e46284b-39c8-4ac1-9696-e1f1d0ce2283" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>