<Workspace Version="0.9.1.4062" X="-2283.41554321926" Y="1046.03030449677" zoom="0.873239338949523" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="a3225b3c-3a95-4e5c-8db5-276ffc4d882a" type="PythonNodeModels.PythonNode" nickname="Filter needed [Rev Clouds]" x="2861.58427353943" y="-1116.43655903527" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import TaskDialog
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
clr.ImportExtensions(Revit.GeometryConversion)
 
doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
 
import sys
import System

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

hidName = IN[0]

revClouds = FilteredElementCollector(doc).OfClass(RevisionCloud).WhereElementIsNotElementType()

res = []

revnames=[]
for c in revClouds:
	rn = doc.GetElement(c.RevisionId).Name
	revnames.append(rn)
	if rn == hidName:
		res.append(c)

ownvs=[]	
for r in res:
	ownvs.append(doc.GetElement(r.OwnerViewId))


# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)
try:
	for i in range(len(res)):
		ownvs[i].HideElementTemporary(res[i].Id)

except:
    pass
 
# End Transaction
TransactionManager.Instance.TransactionTaskDone()
doc.Regenerate()


#Assign your output to the OUT variable.
OUT = res,ownvs</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.StringInput guid="1dd0cb55-fa66-458e-8ee7-721b20f11ec9" type="CoreNodeModels.Input.StringInput" nickname="[Revision]" x="2646.66834813446" y="-1120.26178480496" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>Seq. 1 - Revision 1</System.String>
      <System.String value="Seq. 1 - Revision 1" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Watch guid="303910ff-afc7-4d70-b126-19c9a88219b0" type="CoreNodeModels.Watch" nickname="Watch" x="3129.75430539417" y="-1065.00586184397" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a3225b3c-3a95-4e5c-8db5-276ffc4d882a" start_index="0" end="303910ff-afc7-4d70-b126-19c9a88219b0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1dd0cb55-fa66-458e-8ee7-721b20f11ec9" start_index="0" end="a3225b3c-3a95-4e5c-8db5-276ffc4d882a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>