{
  "Uuid": "63984810-6ed0-4660-997d-96949627777e",
  "IsCustomNode": false,
  "Description": null,
  "Name": "QTO-Wall-210419",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "23cb2b7e-ef8a-4bff-9c7e-e6b6b1cf0ffe-0072498a"
      ],
      "Id": "40c89ce0d689460cabeb3c597d0704ff",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7e58cd76ed574c3cadde68be241601ef",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "a9e961af-1e27-455d-a729-15e2eda2e3c9-0074bdee"
      ],
      "Id": "b38dfa0fad464d3c88748a9fdb5cd2b6",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "0baac5cf824f48c3aae6ed1142726fcd",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys,os,json,tempfile\r\nfrom shutil import copyfile\r\nfrom json import *\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\nclr.AddReference('RevitAPIUI')\r\nfrom Autodesk.Revit.UI import TaskDialog\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\nfrom System.Collections.Generic import *\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\n## add module director\r\ndynPyDir = r\"\\\\hcmcfcfs01\\databim$\\BimESC\\00-BIM STANDARD\\PYTHON\\pythondynamo\"\r\nsys.path.append(dynPyDir)\r\nimport pyDyn\r\nfrom pyDyn import *\r\n##\r\n\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\nelement = UnwrapElement(IN[0])\r\nrevitLink = UnwrapElement(IN[1])\r\nrevitLink_Doc = getLinkDoc(revitLink)\r\n# Place your code below this line\r\ncatName1 = \"Structural Columns\"\r\ncatName2 = \"Structural Framing\"\r\ncatNames = \"\"\"Structural Foundations\r\nStructural Framing\r\nStructural Columns\r\nWalls\r\nFloors\"\"\"\r\nintersect_elements = allElemsIntersected(element,doc)\r\nintersect_LinkElements = allElemsIntersected(element,revitLink_Doc)\r\nintersect_columns = allElemsIntersectedOfCat(element,catName1,revitLink_Doc)\r\nintersect_beams = allElemsIntersectedOfCat(element,catName2,revitLink_Doc)\r\nlocationCurve = getLocationCurve(element)\r\n\r\n\r\n# Assign your output to the OUT variable.\r\nOUT = next(intersect_columns)",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "7382591cc9b747ed945b188ebb0a25ae",
      "Inputs": [
        {
          "Id": "0ebbe7d76dd74a1b8bfcdbffcdedc6ec",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5dcd51fd95bd4fa4bc023af7b307bdd3",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0713368a89e0459d865b3bfd398953f5",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "c1203646b5bb41039795c1542ac34cf4",
      "Inputs": [
        {
          "Id": "2bede8c4d6b24637ba58f5e9e3b064c2",
          "Name": "",
          "Description": "Node to evaluate.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6d574c5f673f41d291a50a1682bcc79c",
          "Name": "",
          "Description": "Watch contents.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualize the output of node."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys, os\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nimport Autodesk.DesignScript.Geometry\r\nfrom Autodesk.DesignScript.Geometry import *\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\n\r\n# Place your code below this line\r\npath1 = os.path.abspath(Autodesk.DesignScript.__file__)\r\n\r\npath2 = os.path.dirname(Autodesk.DesignScript.Geometry.__file__)\r\n# Assign your output to the OUT variable.\r\nOUT = clr.References[2].Location,dir(clr.References[2].Autodesk.DesignScript.Geometry),dir(clr)",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "feafe11ebc484ce58bcb025f3d33b059",
      "Inputs": [
        {
          "Id": "7fb571a3e13c48eda56f9a2d39490478",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e92672a8005c4719aeae6c4cdfd8a078",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "b7fd54508f7d47d8b730cc1b44514d7f",
      "Inputs": [
        {
          "Id": "edb49eb83ee24127b0a1a0551f6b2139",
          "Name": "",
          "Description": "Node to evaluate.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8b6e3dc3efbb4cc99c35df46e3da1942",
          "Name": "",
          "Description": "Watch contents.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualize the output of node."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.Solids",
      "Id": "c993fa9dbff54544bccb185cd990a9dc",
      "Inputs": [
        {
          "Id": "abe0e9ca60ce455fa7bd136fe16c459e",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "56f012938478450c80e6f064e7c1025b",
          "Name": "Solid[]",
          "Description": "Solid[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Solids in this Element\n\nElement.Solids: Solid[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.GetLocation",
      "Id": "b5e2b43661a149b5a79b62fddeae93aa",
      "Inputs": [
        {
          "Id": "dc7a6b4f7df24d34a2b83838bb9c1b16",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4fda4def047147ee8fd6f2fca03fc963",
          "Name": "Geometry",
          "Description": "Location Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get an existing element's location\n\nElement.GetLocation ( ): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Intersect@Autodesk.DesignScript.Geometry.Geometry",
      "Id": "ead88289fd524eae89e77c92886761cb",
      "Inputs": [
        {
          "Id": "75b0f56a69b44e87aabb5be0555f9996",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c86086194fe84a1e858d27f08a340c5c",
          "Name": "other",
          "Description": "Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2e78e64189414a20a74f3f0ef51a3949",
          "Name": "Geometry[]",
          "Description": "Geometry[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the intersection Geometry for this object and another\n\nGeometry.Intersect (other: Geometry): Geometry[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByLineAndPoint@Autodesk.DesignScript.Geometry.Line,Autodesk.DesignScript.Geometry.Point",
      "Id": "c290e1ba8e8b42b3a6eec69801a03bd8",
      "Inputs": [
        {
          "Id": "4e8f33cb26604f4a8b770628ebbca9fd",
          "Name": "line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "34d9f049cce147e8900d9277b4a3a74d",
          "Name": "point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "51230ee3d7ab4880847cad84b7d15db8",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create the Plane containing the input Line and external Point. Point cannot lie on the Line or in the Line axis.\n\nPlane.ByLineAndPoint (line: Line, point: Point): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Id": "9e0dd85f7002406e8a5d5b60236ded79",
      "Inputs": [
        {
          "Id": "118c4328f3644e6aaa05b2829e89634e",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "74790981cef04ec3bde3dd858d30fa31",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector,double",
      "Id": "17a190a9b62d4e5ba2c4646723f1a7d6",
      "Inputs": [
        {
          "Id": "a129f2aa952c4f13bada45859474a617",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9068c491eea341e0b285d5486c2f192d",
          "Name": "direction",
          "Description": "Displacement direction.\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "14bbfe33344849f282d90940ea231b9c",
          "Name": "distance",
          "Description": "Displacement distance along given direction.\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a01cfa1a0ecb4e989b3e9e02116452ed",
          "Name": "Geometry",
          "Description": "Transformed Geometry.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Translates any geometry type by the given distance in the given direction.\n\nGeometry.Translate (direction: Vector, distance: double): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Id": "81cca2ad176d42af80b264a8d6bef06d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "141989e42d8441d48a812660e6356253",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "100;",
      "Id": "70c43f85ce8a401d9a774f888a866d3c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "5ed06e7cd837413d86a54a5855d39f60",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PerimeterCurves",
      "Id": "8d1df2fa8d73479491c6637ff3790561",
      "Inputs": [
        {
          "Id": "8fd278df7c19451bbbc543727f7d89ca",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1c49f3385c3749859f05747aa9adc60a",
          "Name": "Curve[]",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return all the boundary Curves of the Surface.\n\nSurface.PerimeterCurves ( ): Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.SubtractFrom@Autodesk.DesignScript.Geometry.Solid",
      "Id": "dee1fa09f13340d291afc2ac64a36027",
      "Inputs": [
        {
          "Id": "62082c1f96124efdb365ac1e08b6f186",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "671aaada59e7418a8fe838c03bca0c40",
          "Name": "trimmingEntity",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1e4004aec0a74174a841b6abb6e3d21f",
          "Name": "Geometry[]",
          "Description": "Geometry[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Subtract the input tools from this Surface.\n\nSurface.SubtractFrom (trimmingEntity: Solid): Geometry[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.Solids",
      "Id": "a9d947cc26db449abd028a4044c775e4",
      "Inputs": [
        {
          "Id": "db30a1a580cd403ba060e1c4951bc420",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3b5db5dbb928407b9b28f37773171854",
          "Name": "Solid[]",
          "Description": "Solid[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Solids in this Element\n\nElement.Solids: Solid[]"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys,os,json,tempfile\r\nfrom shutil import copyfile\r\nfrom json import *\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\nclr.AddReference('RevitAPIUI')\r\nfrom Autodesk.Revit.UI import TaskDialog\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\nfrom System.Collections.Generic import *\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\n## add module director\r\ndynPyDir = r\"\\\\hcmcfcfs01\\databim$\\BimESC\\00-BIM STANDARD\\PYTHON\\pythondynamo\"\r\nsys.path.append(dynPyDir)\r\nimport pyDyn\r\nfrom pyDyn import *\r\n##\r\n\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\nelement = UnwrapElement(IN[0])\r\nrevitLink = UnwrapElement(IN[1])\r\nrevitLink_Doc = getLinkDoc(revitLink)\r\n# Place your code below this line\r\ncatName1 = \"Structural Columns\"\r\ncatName2 = \"Structural Framing\"\r\ncatNames = \"\"\"Structural Foundations\r\nStructural Framing\r\nStructural Columns\r\nWalls\r\nFloors\"\"\"\r\nintersect_elements = allElemsIntersected(element,doc)\r\nintersect_LinkElements = allElemsIntersected(element,revitLink_Doc)\r\nintersect_columns = allElemsIntersectedOfCat(element,catName1,revitLink_Doc)\r\nintersect_beams = allElemsIntersectedOfCat(element,catName2,revitLink_Doc)\r\nlocationCurve = getLocationCurve(element)\r\n\r\n\r\n# Assign your output to the OUT variable.\r\nOUT = next(intersect_beams)",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "4a8843768f4c4ff3bd2abe0cc8af0394",
      "Inputs": [
        {
          "Id": "4a16529c2adb4b5ebdadd15e85b45d8e",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "355cc59d765f419d92b5cf1bc45eb1e0",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d5e55ed0e09144498a94556589f39293",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.Solids",
      "Id": "5f574a5f0a4f4f28a1837fbd26b8005c",
      "Inputs": [
        {
          "Id": "e8d8377335534880a7e5461c5f9e0252",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "48a6f4e9018649808e765f1f6f1bf26b",
          "Name": "Solid[]",
          "Description": "Solid[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Solids in this Element\n\nElement.Solids: Solid[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.SubtractFrom@Autodesk.DesignScript.Geometry.Solid",
      "Id": "81326a714bc94e1d860287fd1a300dc9",
      "Inputs": [
        {
          "Id": "cdbe9ec7cb9a4acbba98fe1518f3cda7",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5cd58824989f4489ae06e36d1c9e6dfc",
          "Name": "trimmingEntity",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ac951a3bcffc472bb199188ff52aeb23",
          "Name": "Geometry[]",
          "Description": "Geometry[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Subtract the input tools from this Surface.\n\nSurface.SubtractFrom (trimmingEntity: Solid): Geometry[]"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys,os,json,tempfile\r\nfrom shutil import copyfile\r\nfrom json import *\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nimport Autodesk.DesignScript.Geometry\r\nfrom Autodesk.DesignScript.Geometry import *\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\nimport Autodesk.Revit.DB.BooleanOperationsUtils as BOU\r\nimport Autodesk.Revit.DB.SolidSolidCutUtils as SSUT\r\n\r\nclr.AddReference('RevitAPIUI')\r\nfrom Autodesk.Revit.UI import TaskDialog\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\nfrom System.Collections.Generic import *\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\n## add module director\r\ndynPyDir = r\"\\\\hcmcfcfs01\\databim$\\BimESC\\00-BIM STANDARD\\PYTHON\\pythondynamo\"\r\nsys.path.append(dynPyDir)\r\nimport pyDyn\r\nfrom pyDyn import *\r\n##\r\n\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\nelement = UnwrapElement(IN[0])\r\nrevitLink = UnwrapElement(IN[1])\r\nrevitLink_Doc = getLinkDoc(revitLink)\r\n# Place your code below this line\r\ncatName1 = \"Structural Columns\"\r\ncatName2 = \"Structural Framing\"\r\ncatNames = \"\"\"Structural Foundations\r\nStructural Framing\r\nStructural Columns\r\nWalls\r\nFloors\"\"\"\r\nintersect_elements = allElemsIntersected(element,doc)\r\nintersect_LinkElements = allElemsIntersected(element,revitLink_Doc)\r\nintersect_columns = allElemsIntersectedOfCat(element,catName1,revitLink_Doc)\r\nintersect_beams = allElemsIntersectedOfCat(element,catName2,revitLink_Doc)\r\nlocationCurve = getLocationCurve(element)\r\n\r\nelement_Solid = UnionSolid(getSolids(element))\r\nintersect_beam_solids = [UnionSolid(getSolids(beam)) for beam in intersect_beams]\r\n\r\nintersect_solids = []\r\nfor beam_solid in intersect_beam_solids:\r\n\ttry:\r\n\t\tintersect = BOU.ExecuteBooleanOperation(element_Solid,beam_solid,BooleanOperationsType.Intersect)\r\n\t\tdifferent = BOU.ExecuteBooleanOperation(element_Solid,beam_solid,BooleanOperationsType.Difference)#SSUT.AddCutBetweenSolids(doc,beam_solid,element_Solid)#\r\n\t\tunion = BOU.ExecuteBooleanOperation(element_Solid,beam_solid,BooleanOperationsType.Union)\r\n\t\tflag = beam_solid.Volume + element_Solid.Volume - union.Volume == intersect.Volume\r\n\t\tif not flag:\r\n\t\t\tintersect_solids.append(beam_solid)\r\n\texcept Exception, ex:\r\n\t\tintersect_solids.append(ex)\r\n\t\tpass\r\n# Assign your output to the OUT variable.\r\nOUT = intersect_solids#dir(element_Solid)",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "7e22100c92ef4525b9b9ba996087feaf",
      "Inputs": [
        {
          "Id": "2559b2acd5a840bdbd284aba8ede9e08",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "da89de1285794829b6a245fcc19684db",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "75080ad4c6234a7cbe17cc2b5eb893ed",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "1114d26bc71646f98a62a4f52e9c277d",
      "Inputs": [
        {
          "Id": "f152cf380af64aeea08e16d6faa09457",
          "Name": "",
          "Description": "Node to evaluate.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1d59c0165fe94858b58cd109414ea712",
          "Name": "",
          "Description": "Watch contents.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualize the output of node."
    }
  ],
  "Connectors": [
    {
      "Start": "7e58cd76ed574c3cadde68be241601ef",
      "End": "0ebbe7d76dd74a1b8bfcdbffcdedc6ec",
      "Id": "7e3072e4c87c4f6484da3b335d8f4476"
    },
    {
      "Start": "7e58cd76ed574c3cadde68be241601ef",
      "End": "abe0e9ca60ce455fa7bd136fe16c459e",
      "Id": "cbbe202971e74c7099489e5293b7af2e"
    },
    {
      "Start": "7e58cd76ed574c3cadde68be241601ef",
      "End": "dc7a6b4f7df24d34a2b83838bb9c1b16",
      "Id": "8f3da7e3018643c2a0a85163ebdc4d5a"
    },
    {
      "Start": "7e58cd76ed574c3cadde68be241601ef",
      "End": "4a16529c2adb4b5ebdadd15e85b45d8e",
      "Id": "7f9d80f69c214fa19e05ef09a6611b0a"
    },
    {
      "Start": "7e58cd76ed574c3cadde68be241601ef",
      "End": "2559b2acd5a840bdbd284aba8ede9e08",
      "Id": "90d533649a3444be8faa6ce4077c4110"
    },
    {
      "Start": "0baac5cf824f48c3aae6ed1142726fcd",
      "End": "5dcd51fd95bd4fa4bc023af7b307bdd3",
      "Id": "e49e7293f970456790b0e0f11fad4ee4"
    },
    {
      "Start": "0baac5cf824f48c3aae6ed1142726fcd",
      "End": "355cc59d765f419d92b5cf1bc45eb1e0",
      "Id": "c0cc0b15cf074b8fb0e9567bdb96c938"
    },
    {
      "Start": "0baac5cf824f48c3aae6ed1142726fcd",
      "End": "da89de1285794829b6a245fcc19684db",
      "Id": "195c3e58a081463c87e1db4c224a03d8"
    },
    {
      "Start": "0713368a89e0459d865b3bfd398953f5",
      "End": "2bede8c4d6b24637ba58f5e9e3b064c2",
      "Id": "634030fd9afb40ff8d7d06937c8216c4"
    },
    {
      "Start": "6d574c5f673f41d291a50a1682bcc79c",
      "End": "db30a1a580cd403ba060e1c4951bc420",
      "Id": "85cca9fe162b4c94a109bf2c84a10fe1"
    },
    {
      "Start": "e92672a8005c4719aeae6c4cdfd8a078",
      "End": "edb49eb83ee24127b0a1a0551f6b2139",
      "Id": "798b16ce714848829ee2ffdba84b382e"
    },
    {
      "Start": "56f012938478450c80e6f064e7c1025b",
      "End": "75b0f56a69b44e87aabb5be0555f9996",
      "Id": "b5345276cc604c85b9f4b1636efa412e"
    },
    {
      "Start": "4fda4def047147ee8fd6f2fca03fc963",
      "End": "4e8f33cb26604f4a8b770628ebbca9fd",
      "Id": "5c402c2cfc404877a8e6352c0d8495fb"
    },
    {
      "Start": "4fda4def047147ee8fd6f2fca03fc963",
      "End": "118c4328f3644e6aaa05b2829e89634e",
      "Id": "33d1eb8d44554360b70482e75dcfa68c"
    },
    {
      "Start": "2e78e64189414a20a74f3f0ef51a3949",
      "End": "8fd278df7c19451bbbc543727f7d89ca",
      "Id": "9be7f08fc64941118dbc96a2af0fa278"
    },
    {
      "Start": "2e78e64189414a20a74f3f0ef51a3949",
      "End": "62082c1f96124efdb365ac1e08b6f186",
      "Id": "77ab80686c4e49a18ff2c95fdebfe3cf"
    },
    {
      "Start": "51230ee3d7ab4880847cad84b7d15db8",
      "End": "c86086194fe84a1e858d27f08a340c5c",
      "Id": "d488ea6c891c4eae9cec1350f50850d6"
    },
    {
      "Start": "74790981cef04ec3bde3dd858d30fa31",
      "End": "a129f2aa952c4f13bada45859474a617",
      "Id": "0f27d444877e4bc18a59b44053f2e1d8"
    },
    {
      "Start": "a01cfa1a0ecb4e989b3e9e02116452ed",
      "End": "34d9f049cce147e8900d9277b4a3a74d",
      "Id": "c98ec5cff1054a55b98973031a9f3a3b"
    },
    {
      "Start": "141989e42d8441d48a812660e6356253",
      "End": "9068c491eea341e0b285d5486c2f192d",
      "Id": "2082a2d1835c4c4a90188c540262e86b"
    },
    {
      "Start": "5ed06e7cd837413d86a54a5855d39f60",
      "End": "14bbfe33344849f282d90940ea231b9c",
      "Id": "e1f2b98807a547668be26f2424060166"
    },
    {
      "Start": "1e4004aec0a74174a841b6abb6e3d21f",
      "End": "cdbe9ec7cb9a4acbba98fe1518f3cda7",
      "Id": "44c65f15f8c9472fbabc2782ec8b1a76"
    },
    {
      "Start": "3b5db5dbb928407b9b28f37773171854",
      "End": "671aaada59e7418a8fe838c03bca0c40",
      "Id": "9c7b668469a948e89fd2b9a58c01b5d0"
    },
    {
      "Start": "d5e55ed0e09144498a94556589f39293",
      "End": "e8d8377335534880a7e5461c5f9e0252",
      "Id": "394c13a0077145f58d6e78dbedca8428"
    },
    {
      "Start": "48a6f4e9018649808e765f1f6f1bf26b",
      "End": "5cd58824989f4489ae06e36d1c9e6dfc",
      "Id": "7408ab15b4f34610917bc6f9f7eef25f"
    },
    {
      "Start": "75080ad4c6234a7cbe17cc2b5eb893ed",
      "End": "f152cf380af64aeea08e16d6faa09457",
      "Id": "fdcb4a0504174e10bf96dea4913c1ac7"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.10.0.3455",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 66653.514610038692,
      "EyeY": 33024.118129708913,
      "EyeZ": -34256.071410216835,
      "LookX": -31840.180310088144,
      "LookY": -21554.056374837783,
      "LookZ": 38366.164631377433,
      "UpX": -0.12185540419441243,
      "UpY": 0.98162718344767153,
      "UpZ": 0.14683096807289608
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Select Model Element",
        "Id": "40c89ce0d689460cabeb3c597d0704ff",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -359.69593410287951,
        "Y": 97.976402044269719
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Element-Link revit",
        "Id": "b38dfa0fad464d3c88748a9fdb5cd2b6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -361.10903421235287,
        "Y": 238.7616977019369
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "7382591cc9b747ed945b188ebb0a25ae",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 217.33506927164041,
        "Y": 156.40046479067513
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "c1203646b5bb41039795c1542ac34cf4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 504.36139460102265,
        "Y": 107.13419746048413
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script-Check ProtoGeometry.dll",
        "Id": "feafe11ebc484ce58bcb025f3d33b059",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -332.59824600644993,
        "Y": 570.62663957534994
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "b7fd54508f7d47d8b730cc1b44514d7f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 81.880592317143055,
        "Y": 583.41544661312741
      },
      {
        "ShowGeometry": false,
        "Name": "Element.Solids",
        "Id": "c993fa9dbff54544bccb185cd990a9dc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 222.08723409106045,
        "Y": -515.99784401609418
      },
      {
        "ShowGeometry": true,
        "Name": "Element.GetLocation",
        "Id": "b5e2b43661a149b5a79b62fddeae93aa",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 221.42242607447469,
        "Y": -386.51381870773093
      },
      {
        "ShowGeometry": false,
        "Name": "Geometry.Intersect",
        "Id": "ead88289fd524eae89e77c92886761cb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1400.654522367483,
        "Y": -511.14864761851624
      },
      {
        "ShowGeometry": true,
        "Name": "Plane.ByLineAndPoint",
        "Id": "c290e1ba8e8b42b3a6eec69801a03bd8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1122.1497104460775,
        "Y": -361.51011296095987
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.StartPoint",
        "Id": "9e0dd85f7002406e8a5d5b60236ded79",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 643.72837132844586,
        "Y": -265.71951869286704
      },
      {
        "ShowGeometry": true,
        "Name": "Geometry.Translate",
        "Id": "17a190a9b62d4e5ba2c4646723f1a7d6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 887.73826145390922,
        "Y": -253.04025600565251
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.ZAxis",
        "Id": "81cca2ad176d42af80b264a8d6bef06d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 653.16816395550916,
        "Y": -126.24554537113579
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "70c43f85ce8a401d9a774f888a866d3c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 665.977907154759,
        "Y": -28.365944441831175
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.PerimeterCurves",
        "Id": "8d1df2fa8d73479491c6637ff3790561",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 1743.2453032977294,
        "Y": -494.04380201923448
      },
      {
        "ShowGeometry": false,
        "Name": "Surface.SubtractFrom",
        "Id": "dee1fa09f13340d291afc2ac64a36027",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1615.7299068964958,
        "Y": -253.09429196315813
      },
      {
        "ShowGeometry": false,
        "Name": "Element.Solids",
        "Id": "a9d947cc26db449abd028a4044c775e4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 933.01585065333268,
        "Y": 78.2695382541338
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "4a8843768f4c4ff3bd2abe0cc8af0394",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 230.29461076681383,
        "Y": 352.77787147134262
      },
      {
        "ShowGeometry": true,
        "Name": "Element.Solids",
        "Id": "5f574a5f0a4f4f28a1837fbd26b8005c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 512.12480315783455,
        "Y": 315.84118812590214
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.SubtractFrom",
        "Id": "81326a714bc94e1d860287fd1a300dc9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1936.8887886779457,
        "Y": -111.59856102603021
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "7e22100c92ef4525b9b9ba996087feaf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 230.07073381530478,
        "Y": 565.88406478451293
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "1114d26bc71646f98a62a4f52e9c277d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 409.44380626521388,
        "Y": 540.10527432495371
      }
    ],
    "Annotations": [],
    "X": 282.841466644903,
    "Y": -18.328341719760033,
    "Zoom": 0.70256983040215759
  }
}