{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "test geo",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength@double,double",
      "Id": "7dc8eb573e3c42188c69ab1a2302a583",
      "Inputs": [
        {
          "Id": "12803955a5944fa0b575281f9273fd41",
          "Name": "width",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f7c695fb6a154977ac653850fd7e0bee",
          "Name": "length",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1fd732a94d354ebdac99efa9bd64fc03",
          "Name": "Rectangle",
          "Description": "Rectangle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Rectangle centered at the WCS origin in the WCS XY Plane, with specified width (X Axis length), and length (Y Axis length).\n\nRectangle.ByWidthLength (width: double = 1, length: double = 1): Rectangle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "10;",
      "Id": "e92e34722e67472eaea81e73ed9772e3",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7063ce9e68524f6c94a5ff8bd0c63806",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "623e1180653e4ac0ad054d29688f15b3",
      "Inputs": [
        {
          "Id": "810408c6586343e0b6780853fc68ad14",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "affb0a4d705a46f39f84d69d3070ffcc",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2af235b786a2458e9d08cc43c6368b37",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "bfd4986ccc8d4531bdac5fe8a23ed4ea",
      "Inputs": [
        {
          "Id": "ade209593abb4b9dadd41d86327f6d4a",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "794f9c92b55946edb47d4e0a1f6a0b66",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7fae49bd70cc49a48cb3da3d2f10df9b",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d2943477cab84f0192090766420bfce4",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "4aaa4212c2e14fbd9d2087f5eb7183f1",
      "Inputs": [
        {
          "Id": "89ef781164f74f5f9eb1aa8c8ee7bd77",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b5835db20f564747b29a5a4f7d884388",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2edc742d2440428694c12b2ede382855",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f145f3d4ab2542f99a17cfa2aba81404",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector,double",
      "Id": "7c1df46886774544941570d833024f77",
      "Inputs": [
        {
          "Id": "adfedd6930564da49cab3f1c0b783ce1",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "844aeee7b1284e7bb43647299037f51b",
          "Name": "direction",
          "Description": "Displacement direction.\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8a0d529c38714126b73e04f7f892ab82",
          "Name": "distance",
          "Description": "Displacement distance along given direction.\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9696f6493fa041589f0a55b850523280",
          "Name": "Geometry",
          "Description": "Transformed Geometry.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Translates any geometry type by the given distance in the given direction.\n\nGeometry.Translate (direction: Vector, distance: double): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Id": "4b87e44c1948493eb11186fcf652328c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b547652fb41d49b4b6409cc88f89e0cd",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "c5222e3c4b0045e2b5cfff545535492f",
      "Inputs": [
        {
          "Id": "cdbcdf1e61b144acb2cafaa310fab9b6",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "93c25025cbd74b6f9dd144950e0106bb",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid by lofting between input cross section closed Curves.\n\nSolid.ByLoft (crossSections: Curve[]): Solid"
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "601cb940a8d84f72904d95e35a25cf1f",
      "Inputs": [
        {
          "Id": "89466faef47f47c980a49889c8c7768c",
          "Name": "item0",
          "Description": "Item Index #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b235768ca2c4491ab4ffa05b5e934b8e",
          "Name": "item1",
          "Description": "Item Index #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8bbd8d8d1a6742aa92c7cf1f487f182d",
          "Name": "list",
          "Description": "A list (type: var[]..[])",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Makes a new list out of the given inputs"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByLineAndPoint@Autodesk.DesignScript.Geometry.Line,Autodesk.DesignScript.Geometry.Point",
      "Id": "3b9cfd9a807b43f4b7f5204e1255fb42",
      "Inputs": [
        {
          "Id": "2216308b5fe94b04890e62347cf301ce",
          "Name": "line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4952ff8cdd7d4db5bd4f286a24908851",
          "Name": "point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "eb0d6edddfbb4a41be4a3f5eb6a74544",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create the Plane containing the input Line and external Point. Point cannot lie on the Line or in the Line axis.\n\nPlane.ByLineAndPoint (line: Line, point: Point): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "e64c13ffb7f6437a95bb1e5bdd16be71",
      "Inputs": [
        {
          "Id": "5a97e136078f4ca4a09c5bdb3ced3de9",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e0aeb1f31ae245219cd12a9f903357b8",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "951712b8426e4583913bb42b5f0a56d2",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "46d5adab025d4a7e88c34228f0af0f6c",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Intersect@Autodesk.DesignScript.Geometry.Geometry",
      "Id": "dd57ab50c370411abd9464ba8a660e19",
      "Inputs": [
        {
          "Id": "bd83a3e7637d4632b70b3336655ffccd",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "aa1c80efb6c347b396294fdd288b1c1c",
          "Name": "other",
          "Description": "Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9b23f210d4934c29ab43bd197e01c73d",
          "Name": "Geometry[]",
          "Description": "Geometry[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the intersection Geometry for this object and another\n\nGeometry.Intersect (other: Geometry): Geometry[]"
    }
  ],
  "Connectors": [
    {
      "Start": "1fd732a94d354ebdac99efa9bd64fc03",
      "End": "adfedd6930564da49cab3f1c0b783ce1",
      "Id": "08b8cdebac6448d1b1d64f717edc51aa"
    },
    {
      "Start": "1fd732a94d354ebdac99efa9bd64fc03",
      "End": "b235768ca2c4491ab4ffa05b5e934b8e",
      "Id": "ef427b08426945f8885ba9def5018588"
    },
    {
      "Start": "7063ce9e68524f6c94a5ff8bd0c63806",
      "End": "12803955a5944fa0b575281f9273fd41",
      "Id": "9a65d16e60514d9bae2e615917c9c7a0"
    },
    {
      "Start": "7063ce9e68524f6c94a5ff8bd0c63806",
      "End": "f7c695fb6a154977ac653850fd7e0bee",
      "Id": "7ff63323608b47f6b8cfa0eb6802b238"
    },
    {
      "Start": "7063ce9e68524f6c94a5ff8bd0c63806",
      "End": "8a0d529c38714126b73e04f7f892ab82",
      "Id": "27abc8a2e76a45dc916ac858fc4245c8"
    },
    {
      "Start": "7063ce9e68524f6c94a5ff8bd0c63806",
      "End": "89ef781164f74f5f9eb1aa8c8ee7bd77",
      "Id": "ce8134c7d06448a8a0cf3a678a029280"
    },
    {
      "Start": "7063ce9e68524f6c94a5ff8bd0c63806",
      "End": "951712b8426e4583913bb42b5f0a56d2",
      "Id": "eeaa5c45ceed4ec9b38e6352e6030b71"
    },
    {
      "Start": "2af235b786a2458e9d08cc43c6368b37",
      "End": "2216308b5fe94b04890e62347cf301ce",
      "Id": "e3388e96ab45470fb124d976fb183cd5"
    },
    {
      "Start": "d2943477cab84f0192090766420bfce4",
      "End": "810408c6586343e0b6780853fc68ad14",
      "Id": "4726f383047d41a2a5d0bc40c8ae225d"
    },
    {
      "Start": "f145f3d4ab2542f99a17cfa2aba81404",
      "End": "affb0a4d705a46f39f84d69d3070ffcc",
      "Id": "b1cd4c992c32451bbbf07471ec67aacc"
    },
    {
      "Start": "9696f6493fa041589f0a55b850523280",
      "End": "89466faef47f47c980a49889c8c7768c",
      "Id": "039bd28c21f74619b910fdad99a25b13"
    },
    {
      "Start": "b547652fb41d49b4b6409cc88f89e0cd",
      "End": "844aeee7b1284e7bb43647299037f51b",
      "Id": "320e7cba7c97456a9168e8e6d6cee4b8"
    },
    {
      "Start": "93c25025cbd74b6f9dd144950e0106bb",
      "End": "bd83a3e7637d4632b70b3336655ffccd",
      "Id": "9bbff8648cfb4adb84489c599f9ca1e4"
    },
    {
      "Start": "8bbd8d8d1a6742aa92c7cf1f487f182d",
      "End": "cdbcdf1e61b144acb2cafaa310fab9b6",
      "Id": "4b84cdabad2f42ce84f89167722042d2"
    },
    {
      "Start": "eb0d6edddfbb4a41be4a3f5eb6a74544",
      "End": "aa1c80efb6c347b396294fdd288b1c1c",
      "Id": "f66c64ad223749d6a6a0c0c3dd8d6b0c"
    },
    {
      "Start": "46d5adab025d4a7e88c34228f0af0f6c",
      "End": "4952ff8cdd7d4db5bd4f286a24908851",
      "Id": "ba2f6d43b2ff4ff2ab3331cb3b60bc78"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.10.0.3455",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -23.145908355712891,
      "EyeY": 41.208633422851563,
      "EyeZ": 41.347381591796875,
      "LookX": 18.145908355712891,
      "LookY": -30.208633422851563,
      "LookZ": -49.347381591796875,
      "UpX": 0.10378085821866989,
      "UpY": 0.95371699333190918,
      "UpZ": -0.28222957253456116
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Rectangle.ByWidthLength",
        "Id": "7dc8eb573e3c42188c69ab1a2302a583",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 194.73824893486972,
        "Y": 291.86643550040122
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "e92e34722e67472eaea81e73ed9772e3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 19.568254597409236,
        "Y": 436.0
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "623e1180653e4ac0ad054d29688f15b3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 418.49027946056214,
        "Y": 575.2297556362787
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "bfd4986ccc8d4531bdac5fe8a23ed4ea",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 173.06897560065198,
        "Y": 481.62206354274952
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "4aaa4212c2e14fbd9d2087f5eb7183f1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 174.28528036321387,
        "Y": 632.73264413915683
      },
      {
        "ShowGeometry": true,
        "Name": "Geometry.Translate",
        "Id": "7c1df46886774544941570d833024f77",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 396.19561362668293,
        "Y": 94.392613327600657
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.ZAxis",
        "Id": "4b87e44c1948493eb11186fcf652328c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 237.19397898740851,
        "Y": 167.91403491017456
      },
      {
        "ShowGeometry": false,
        "Name": "Solid.ByLoft",
        "Id": "c5222e3c4b0045e2b5cfff545535492f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 886.34375078620371,
        "Y": 320.10724055260869
      },
      {
        "ShowGeometry": true,
        "Name": "List Create",
        "Id": "601cb940a8d84f72904d95e35a25cf1f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 664.33420567746543,
        "Y": 360.96096854851146
      },
      {
        "ShowGeometry": true,
        "Name": "Plane.ByLineAndPoint",
        "Id": "3b9cfd9a807b43f4b7f5204e1255fb42",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 917.88795359236371,
        "Y": 635.57240127076113
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "e64c13ffb7f6437a95bb1e5bdd16be71",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 135.5071817912397,
        "Y": 801.773360249494
      },
      {
        "ShowGeometry": true,
        "Name": "Geometry.Intersect",
        "Id": "dd57ab50c370411abd9464ba8a660e19",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1212.6217956825408,
        "Y": 420.22429128186172
      }
    ],
    "Annotations": [],
    "X": -726.95261204939334,
    "Y": 21.876447454633762,
    "Zoom": 0.92151945135142155
  }
}