<Workspace Version="0.9.1.4062" X="0" Y="0" zoom="1" Name="Filter Revit Structural Elements" Description="" ID="94e3d294-2631-4195-bd1a-7966e0789615" Category="Revit.Selection">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.StringInput guid="e0c03b3d-82dc-425d-b1e2-316ec74dd2f2" type="CoreNodeModels.Input.StringInput" nickname="Category name" x="613.46342814557" y="374" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>Structural Foundations</System.String>
      <System.String value="Structural Foundations" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.StringInput guid="332d7680-642f-4ceb-b2a2-16852e066e0b" type="CoreNodeModels.Input.StringInput" nickname="Category name" x="618.66590708073" y="431.93647176575" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>Walls</System.String>
      <System.String value="Walls" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.StringInput guid="a4522e20-57c7-49b6-851c-c67f1308b84d" type="CoreNodeModels.Input.StringInput" nickname="Category name" x="612" y="497.4940528838" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>Structural Columns</System.String>
      <System.String value="Structural Columns" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.StringInput guid="2d877760-f199-4668-b48f-552ed8eb5702" type="CoreNodeModels.Input.StringInput" nickname="Category name" x="612.91774125994" y="560.82814580307" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>Structural Framing</System.String>
      <System.String value="Structural Framing" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="aefc3de4-e96a-4509-b9c6-727a4ff3dc41" type="PythonNodeModels.PythonNode" nickname="Python Script" x="872.43622154405" y="398.76233881101" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="5">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
elems = IN[0]
cateName1 = IN[1]
cateName2 = IN[2]
cateName3 = IN[3]
cateName4 = IN[4]

res = []

for e in elems:
	ee = UnwrapElement(e)
	cat = ee.Category.Name
	if cat == cateName1 or cat == cateName2 or cat == cateName3 or cat == cateName4:
		res.append(e)

#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="af4f6cc8-63b5-4c27-a80c-31eef0d832b2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="415" y="344" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <Symbol value="RevitElements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9dab9119-a681-484a-b923-a4099f75781e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1141" y="379" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false">
      <Symbol value="StrucElements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e0c03b3d-82dc-425d-b1e2-316ec74dd2f2" start_index="0" end="aefc3de4-e96a-4509-b9c6-727a4ff3dc41" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="332d7680-642f-4ceb-b2a2-16852e066e0b" start_index="0" end="aefc3de4-e96a-4509-b9c6-727a4ff3dc41" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a4522e20-57c7-49b6-851c-c67f1308b84d" start_index="0" end="aefc3de4-e96a-4509-b9c6-727a4ff3dc41" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2d877760-f199-4668-b48f-552ed8eb5702" start_index="0" end="aefc3de4-e96a-4509-b9c6-727a4ff3dc41" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aefc3de4-e96a-4509-b9c6-727a4ff3dc41" start_index="0" end="9dab9119-a681-484a-b923-a4099f75781e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="af4f6cc8-63b5-4c27-a80c-31eef0d832b2" start_index="0" end="aefc3de4-e96a-4509-b9c6-727a4ff3dc41" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="6e06f7a1-8172-41e8-bd23-3f8f85474ca8" annotationText="&lt;Click here to edit the group title&gt;" left="602" top="344" width="404.43622154405" height="284.82814580307" fontSize="14" InitialTop="374" InitialHeight="284.82814580307" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="e0c03b3d-82dc-425d-b1e2-316ec74dd2f2" />
      <Models ModelGuid="332d7680-642f-4ceb-b2a2-16852e066e0b" />
      <Models ModelGuid="a4522e20-57c7-49b6-851c-c67f1308b84d" />
      <Models ModelGuid="2d877760-f199-4668-b48f-552ed8eb5702" />
      <Models ModelGuid="aefc3de4-e96a-4509-b9c6-727a4ff3dc41" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="30033.900390625" eyeY="16968.091796875" eyeZ="19789.55078125" lookX="-29493.548828125" lookY="-13682.4716796875" lookZ="-20414.205078125" upX="-0.121536239981651" upY="0.989015877246857" upZ="-0.084122322499752" />
  </Cameras>
</Workspace>