<Workspace Version="0.9.1.4062" X="0" Y="-16" zoom="1" Name="Get Intersected points of curves" Description="" ID="36deba96-ba99-4f66-9d20-715ebc36a800" Category="Geometry.Curve">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="4d9b335e-fac1-453e-bdd4-d03f5e490fa4" type="PythonNodeModels.PythonNode" nickname="Python Script-Intersect Point" x="7" y="226" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
 

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
curves = IN[0]

def getIntersectPoints(curves):
	res = []	
	still = True
	i = 1
	while i &lt; len(curves):
		c0 = curves[i-1]		
		rest = curves[i:]		
		for c in rest:
			flag = c0.DoesIntersect(c)
			if flag:
				p = c0.Intersect(c)
				res.append(p)
		i+=1
	return res

res = getIntersectPoints(curves)
#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bdf3a66c-fa8e-42d2-b212-b4bb9e5ffefb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-164" y="230" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <Symbol value="curves" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e5c21aff-901f-4a74-9d11-b74cc403e7f5" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="468" y="223" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false">
      <Symbol value="points" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1c9f76d9-c6af-46fc-af50-ba18ac32b660" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="244" y="199" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4d9b335e-fac1-453e-bdd4-d03f5e490fa4" start_index="0" end="1c9f76d9-c6af-46fc-af50-ba18ac32b660" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bdf3a66c-fa8e-42d2-b212-b4bb9e5ffefb" start_index="0" end="4d9b335e-fac1-453e-bdd4-d03f5e490fa4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1c9f76d9-c6af-46fc-af50-ba18ac32b660" start_index="0" end="e5c21aff-901f-4a74-9d11-b74cc403e7f5" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-48739.9140625" eyeY="29137.7109375" eyeZ="-7700.36328125" lookX="-6446.962890625" lookY="-35112.7265625" lookZ="16375.4775390625" upX="-0.284690767526627" upY="0.629320383071899" upZ="0.723123073577881" />
  </Cameras>
</Workspace>