<Workspace Version="0.9.1.4062" X="-327.47804796875" Y="-225.764095578834" zoom="1.545620359375" Name="Revit Category Filterer 1" Description="" ID="0a46c85c-8354-4305-9206-9341170d96bd" Category="Revit.Selection">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f248ebfa-0dcd-48f5-8ab2-9efe7a1dae96" type="PythonNodeModels.PythonNode" nickname="Python Script-Filterer" x="598.08887650995" y="203.44910421525" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
elems = IN[0]
cateName = IN[1]

res = []

for e in elems:
	ee = UnwrapElement(e)
	if ee.Category.Name == cateName:
		res.append(e)

#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8537b6c6-aee7-4bae-9492-62b617072248" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="List Elements" x="253.127504183873" y="326.706021185688" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <Symbol value="elems" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="03665b85-9af2-4bb7-9a8d-253cd4d1e3da" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="CategoryName" x="254.244387662587" y="432.353010592844" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <Symbol value="catName" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2b2a0c6c-5640-479f-b3d5-869ba32b91c3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Category Elements" x="1070.61866752673" y="344.356550827897" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false">
      <Symbol value="elems" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a555c2e2-aacb-4f35-8bbc-3daf022e11b4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="453.848866388125" y="478.619533633712" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="BuiltIn" function="Count@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fcc9900b-9854-4c13-9c0e-24e6f5c578a5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="&gt;" x="618.83116521286" y="478.619533633713" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="Operators" function="&gt;@var[]..[],var[]..[]" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d8804201-7be0-491e-a971-626675a6d1e1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="464" y="566" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="1;" ShouldFocus="false" />
    <CoreNodeModels.Logic.If guid="f6e12415-2ce2-4ca9-b2e3-602580b700b4" type="CoreNodeModels.Logic.If" nickname="If" x="883.449832739591" y="353.750578052639" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
    <PythonNodeModels.PythonNode guid="30cd370d-cf5f-46b8-b59c-eb02f8658a80" type="PythonNodeModels.PythonNode" nickname="Python Script-Filterer" x="596.459588278059" y="337.96622928183" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
elem = UnwrapElement(IN[0])
cateName = IN[1]

res = []
if elem.Category.Name == cateName:
	res.append(elem)

#Assign your output to the OUT variable.
OUT = elem</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f248ebfa-0dcd-48f5-8ab2-9efe7a1dae96" start_index="0" end="f6e12415-2ce2-4ca9-b2e3-602580b700b4" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8537b6c6-aee7-4bae-9492-62b617072248" start_index="0" end="f248ebfa-0dcd-48f5-8ab2-9efe7a1dae96" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8537b6c6-aee7-4bae-9492-62b617072248" start_index="0" end="a555c2e2-aacb-4f35-8bbc-3daf022e11b4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8537b6c6-aee7-4bae-9492-62b617072248" start_index="0" end="30cd370d-cf5f-46b8-b59c-eb02f8658a80" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="03665b85-9af2-4bb7-9a8d-253cd4d1e3da" start_index="0" end="f248ebfa-0dcd-48f5-8ab2-9efe7a1dae96" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="03665b85-9af2-4bb7-9a8d-253cd4d1e3da" start_index="0" end="30cd370d-cf5f-46b8-b59c-eb02f8658a80" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a555c2e2-aacb-4f35-8bbc-3daf022e11b4" start_index="0" end="fcc9900b-9854-4c13-9c0e-24e6f5c578a5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fcc9900b-9854-4c13-9c0e-24e6f5c578a5" start_index="0" end="f6e12415-2ce2-4ca9-b2e3-602580b700b4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d8804201-7be0-491e-a971-626675a6d1e1" start_index="0" end="fcc9900b-9854-4c13-9c0e-24e6f5c578a5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f6e12415-2ce2-4ca9-b2e3-602580b700b4" start_index="0" end="2b2a0c6c-5640-479f-b3d5-869ba32b91c3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="30cd370d-cf5f-46b8-b59c-eb02f8658a80" start_index="0" end="f6e12415-2ce2-4ca9-b2e3-602580b700b4" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>