<Workspace Version="0.9.1.4062" X="634.886217032587" Y="281.86484216577" zoom="0.446685793067653" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="a64f971a-f943-4609-994a-e7feeb8c19de" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements = Walls" x="-1143.74870565641" y="-153.655246314169" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <instance id="0fe7020f-886b-4bf0-a2cc-cd47a47dc955-0004d6c8" />
      <instance id="0fe7020f-886b-4bf0-a2cc-cd47a47dc955-0004d6c9" />
      <instance id="0fe7020f-886b-4bf0-a2cc-cd47a47dc955-0004d6ca" />
      <instance id="0fe7020f-886b-4bf0-a2cc-cd47a47dc955-0004d6cb" />
      <instance id="0fe7020f-886b-4bf0-a2cc-cd47a47dc955-0004d6d6" />
      <instance id="0fe7020f-886b-4bf0-a2cc-cd47a47dc955-0004d6d7" />
      <instance id="0fe7020f-886b-4bf0-a2cc-cd47a47dc955-0004d6d8" />
      <instance id="0fe7020f-886b-4bf0-a2cc-cd47a47dc955-0004d6d9" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0005c210-7907-4f94-b412-43d662b8ad6f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Transaction.Start" x="38.6954276308024" y="-317.707801437098" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Transaction.Transaction.Start@var" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="79baf9d5-be00-4ad4-88d7-7e0bda443fde" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Transaction.End" x="926.777047073718" y="-319.984602092783" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Transaction.Transaction.End@var" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3508d0c7-452b-4581-b8dc-d5430f48ab59" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-368.695999857808" y="-171.222709630339" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="e;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="bc1719a9-18a6-4008-966c-f467f8e0d979" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FirstItem" x="232.84434276558" y="-126.937389664971" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="DSCoreNodes.dll" function="DSCore.List.FirstItem@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b8c53d7c-90d0-4b4e-9b6f-b4c62cfe43f4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.AddItemToFront" x="388.570163826138" y="-150.130597056969" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="DSCoreNodes.dll" function="DSCore.List.AddItemToFront@var[]..[],var[]..[]" />
    <CoreNodeModels.Input.StringInput guid="aa7bdd5d-2d1a-481c-8b95-cd8f18693017" type="CoreNodeModels.Input.StringInput" nickname="2: Unjoin 2 Ends" x="-132.685057041823" y="263.584819528803" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import WallUtils

walls = UnwrapElement(IN[0])

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(walls)):
	WallUtils.DisallowWallJoinAtEnd(walls[i],0)
	WallUtils.DisallowWallJoinAtEnd(walls[i],1)
	
TransactionManager.Instance.TransactionTaskDone()
OUT = "Successfull"</System.String>
      <System.String value="import clr&#xD;&#xA;&#xD;&#xA;clr.AddReference(&quot;RevitServices&quot;)&#xD;&#xA;import RevitServices&#xD;&#xA;from RevitServices.Persistence import DocumentManager&#xD;&#xA;from RevitServices.Transactions import TransactionManager&#xD;&#xA;doc = DocumentManager.Instance.CurrentDBDocument&#xD;&#xA;&#xD;&#xA;clr.AddReference(&quot;RevitAPI&quot;)&#xD;&#xA;from Autodesk.Revit.DB import WallUtils&#xD;&#xA;&#xD;&#xA;walls = UnwrapElement(IN[0])&#xD;&#xA;&#xD;&#xA;TransactionManager.Instance.EnsureInTransaction(doc)&#xD;&#xA;&#xD;&#xA;for i in range(0,len(walls)):&#xD;&#xA;	WallUtils.DisallowWallJoinAtEnd(walls[i],0)&#xD;&#xA;	WallUtils.DisallowWallJoinAtEnd(walls[i],1)&#xD;&#xA;	&#xD;&#xA;TransactionManager.Instance.TransactionTaskDone()&#xD;&#xA;OUT = &quot;Successfull&quot;" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonStringNode guid="357afc57-7516-4c18-86bb-df42548f6072" type="PythonNodeModels.PythonStringNode" nickname="Python Script From String" x="644.82068913741" y="-159.002705846905" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="81596515-98ce-4bcd-89f1-f0225c919ce1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Unjoin Mode&#xD;&#xA;" x="-763.74509362427" y="-67.220997431207" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="0;" ShouldFocus="false" />
    <CoreNodeModels.Input.StringInput guid="6f9fc91c-75a0-4468-9432-e13db54b62f4" type="CoreNodeModels.Input.StringInput" nickname="1: Unjoin End 1" x="-374.50329796116" y="263.928678573319" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import WallUtils

walls = UnwrapElement(IN[0])

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(walls)):
	WallUtils.DisallowWallJoinAtEnd(walls[i],1)
	
TransactionManager.Instance.TransactionTaskDone()
OUT = "Successfull"</System.String>
      <System.String value="import clr&#xD;&#xA;&#xD;&#xA;clr.AddReference(&quot;RevitServices&quot;)&#xD;&#xA;import RevitServices&#xD;&#xA;from RevitServices.Persistence import DocumentManager&#xD;&#xA;from RevitServices.Transactions import TransactionManager&#xD;&#xA;doc = DocumentManager.Instance.CurrentDBDocument&#xD;&#xA;&#xD;&#xA;clr.AddReference(&quot;RevitAPI&quot;)&#xD;&#xA;from Autodesk.Revit.DB import WallUtils&#xD;&#xA;&#xD;&#xA;walls = UnwrapElement(IN[0])&#xD;&#xA;&#xD;&#xA;TransactionManager.Instance.EnsureInTransaction(doc)&#xD;&#xA;&#xD;&#xA;for i in range(0,len(walls)):&#xD;&#xA;	WallUtils.DisallowWallJoinAtEnd(walls[i],1)&#xD;&#xA;	&#xD;&#xA;TransactionManager.Instance.TransactionTaskDone()&#xD;&#xA;OUT = &quot;Successfull&quot;" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.StringInput guid="2a4470ab-cd79-4491-b001-13e825b96825" type="CoreNodeModels.Input.StringInput" nickname="0: Unjoin End 0" x="-610.214279167865" y="265.01688132748" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import WallUtils

walls = UnwrapElement(IN[0])

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(walls)):
	WallUtils.DisallowWallJoinAtEnd(walls[i],0)
	
TransactionManager.Instance.TransactionTaskDone()
OUT = "Successfull"</System.String>
      <System.String value="import clr&#xD;&#xA;&#xD;&#xA;clr.AddReference(&quot;RevitServices&quot;)&#xD;&#xA;import RevitServices&#xD;&#xA;from RevitServices.Persistence import DocumentManager&#xD;&#xA;from RevitServices.Transactions import TransactionManager&#xD;&#xA;doc = DocumentManager.Instance.CurrentDBDocument&#xD;&#xA;&#xD;&#xA;clr.AddReference(&quot;RevitAPI&quot;)&#xD;&#xA;from Autodesk.Revit.DB import WallUtils&#xD;&#xA;&#xD;&#xA;walls = UnwrapElement(IN[0])&#xD;&#xA;&#xD;&#xA;TransactionManager.Instance.EnsureInTransaction(doc)&#xD;&#xA;&#xD;&#xA;for i in range(0,len(walls)):&#xD;&#xA;	WallUtils.DisallowWallJoinAtEnd(walls[i],0)&#xD;&#xA;	&#xD;&#xA;TransactionManager.Instance.TransactionTaskDone()&#xD;&#xA;OUT = &quot;Successfull&quot;" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="8b07dc9d-59ca-4c57-90ec-fe26fa636f94" type="PythonNodeModels.PythonNode" nickname="Python Script" x="240.183275543438" y="125.608082178177" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="4">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
mode = IN[0]
s0 = IN[1]
s1 = IN[2]
s2 = IN[3]

res = []

if mode == 0:
	res = s0
elif mode == 1:
	res = s1
elif mode == 2:
	res = s2
else:
	res = 0
	
#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a64f971a-f943-4609-994a-e7feeb8c19de" start_index="0" end="3508d0c7-452b-4581-b8dc-d5430f48ab59" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0005c210-7907-4f94-b412-43d662b8ad6f" start_index="0" end="bc1719a9-18a6-4008-966c-f467f8e0d979" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0005c210-7907-4f94-b412-43d662b8ad6f" start_index="0" end="b8c53d7c-90d0-4b4e-9b6f-b4c62cfe43f4" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3508d0c7-452b-4581-b8dc-d5430f48ab59" start_index="0" end="0005c210-7907-4f94-b412-43d662b8ad6f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bc1719a9-18a6-4008-966c-f467f8e0d979" start_index="0" end="b8c53d7c-90d0-4b4e-9b6f-b4c62cfe43f4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b8c53d7c-90d0-4b4e-9b6f-b4c62cfe43f4" start_index="0" end="357afc57-7516-4c18-86bb-df42548f6072" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aa7bdd5d-2d1a-481c-8b95-cd8f18693017" start_index="0" end="8b07dc9d-59ca-4c57-90ec-fe26fa636f94" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="357afc57-7516-4c18-86bb-df42548f6072" start_index="0" end="79baf9d5-be00-4ad4-88d7-7e0bda443fde" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="81596515-98ce-4bcd-89f1-f0225c919ce1" start_index="0" end="8b07dc9d-59ca-4c57-90ec-fe26fa636f94" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6f9fc91c-75a0-4468-9432-e13db54b62f4" start_index="0" end="8b07dc9d-59ca-4c57-90ec-fe26fa636f94" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a4470ab-cd79-4491-b001-13e825b96825" start_index="0" end="8b07dc9d-59ca-4c57-90ec-fe26fa636f94" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8b07dc9d-59ca-4c57-90ec-fe26fa636f94" start_index="0" end="357afc57-7516-4c18-86bb-df42548f6072" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="b70d0cf8-a43d-4db3-b7a2-2db80f9a68ae" text="0: Unjoint End 0&#xD;&#xA;1: Unjoint End 1&#xD;&#xA;2: Unjoint 2 Ends" x="-642.434269978068" y="-122.7514404812" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="60eb7743-eb07-4399-b033-36e3cc208296" annotationText="&lt;Click here to edit the group title&gt;" left="222.84434276558" top="-180.130597056969" width="314.725821060558" height="146.193207391998" fontSize="14" InitialTop="-150.130597056969" InitialHeight="146.193207391998" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="bc1719a9-18a6-4008-966c-f467f8e0d979" />
      <Models ModelGuid="b8c53d7c-90d0-4b4e-9b6f-b4c62cfe43f4" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="4aa55f63-2bc4-4eab-8c8b-b79d501da216" annotationText="&lt;Click here to edit the group title&gt;" left="28.6954276308024" top="-349.984602092783" width="1047.08161944292" height="125.276800655685" fontSize="14" InitialTop="-319.984602092783" InitialHeight="125.276800655685" TextblockHeight="20" backgrouund="#FFFF7BAC">
      <Models ModelGuid="0005c210-7907-4f94-b412-43d662b8ad6f" />
      <Models ModelGuid="79baf9d5-be00-4ad4-88d7-7e0bda443fde" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>