<Workspace Version="0.9.1.4062" X="519.163847592773" Y="-80.7024431136888" zoom="1.06060772236021" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="5eab63e8-24f7-4161-9f0d-0042f67332fb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-117.956659592452" y="249.044328145285" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import TaskDialog
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
clr.ImportExtensions(Revit.GeometryConversion)
 
doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
 
import sys
import System
import Autodesk.Revit.DB.JoinGeometryUtils as JGU # de Join 


#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
e = UnwrapElement(IN[0])

res = []

EIEF = ElementIntersectsElementFilter(e[0])
ee = FilteredElementCollector(doc).WherePasses(EIEF).ToElements()
res.append(ee)
	
#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="c3fa0a9a-8a22-4c1d-bcdb-8cba6a8efabd" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-428.210956810786" y="229.776229208825" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <instance id="b003f3e7-f746-49b2-8d42-ec38020e6e4a-0005002c" />
      <instance id="b003f3e7-f746-49b2-8d42-ec38020e6e4a-0005003a" />
    </Dynamo.Nodes.DSModelElementsSelection>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c3fa0a9a-8a22-4c1d-bcdb-8cba6a8efabd" start_index="0" end="5eab63e8-24f7-4161-9f0d-0042f67332fb" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>