<Workspace Version="0.9.1.4062" X="104.106453999858" Y="106.11773326114" zoom="0.680624072494516" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.ElementsOfCategory guid="80171361-c0e1-4a87-9c51-7d42229fcde5" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="461.184033109253" y="140.438847231228" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
    <DSRevitNodesUI.ElementsOfCategory guid="56a20d69-7614-4f28-b585-86e61f7af5d0" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="458.5" y="282.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
    <DSRevitNodesUI.Categories guid="c644802a-96d6-4d3d-acac-6902c03d5506" type="DSRevitNodesUI.Categories" nickname="Categories" x="208.5" y="145.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="931:Walls" />
    <DSRevitNodesUI.Categories guid="4ea11c76-c227-42b6-934f-66e1e57ce8c8" type="DSRevitNodesUI.Categories" nickname="Categories" x="207" y="284" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="344:Floors" />
    <DSRevitNodesUI.Categories guid="d0c85c09-509c-4bf9-b1e5-d483f8dd901a" type="DSRevitNodesUI.Categories" nickname="Categories" x="203" y="390" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="872:StructuralFraming" />
    <DSRevitNodesUI.Categories guid="d35b076e-472a-48c7-8c2f-248b82c7ef3d" type="DSRevitNodesUI.Categories" nickname="Categories" x="205" y="504" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="865:StructuralColumns" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="72b4479b-5c33-4844-8f66-06bde27cb7c8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="675.928620412944" y="124.853790693923" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="dafeef20-fde7-4045-9f25-92f23004ae16" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="674.459684442465" y="284" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="43245b2f-029b-429b-99c2-522325b20d14" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Solids" x="842.20673226688" y="126.543009712227" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Solids" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="90fa7cca-7d18-4a69-b35a-e733da099a47" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Solids" x="834.902970126596" y="292" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Solids" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="446d8020-3c23-4dfd-9e78-92caf0a5e0c3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.ByUnion" x="1029.47938585163" y="130.885811612119" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.ByUnion@Autodesk.DesignScript.Geometry.Solid[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1cbaed5e-3504-47e4-b2b3-a048871d64b7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.ByUnion" x="1028.60894644295" y="293.03434258604" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.ByUnion@Autodesk.DesignScript.Geometry.Solid[]" />
    <Dynamo.Nodes.DSModelElementsSelection guid="22861bf9-3774-406b-8c15-ad7ef68c3a94" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="457.553721550393" y="-39.6559748065824" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" />
    <Dynamo.Nodes.DSModelElementsSelection guid="fa5f76ac-b98b-447a-9d08-489730acec61" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="458.922859481351" y="360.079581294848" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" />
    <PythonNodeModels.PythonNode guid="34c5d48e-2f22-4c4a-ba56-da7974fa28db" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1549.73167921809" y="151.74381808461" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="4">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitAPI")
import Autodesk

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

elementA = UnwrapElement(IN[0])
elementB = UnwrapElement(IN[1])
geo1 = IN[2]
geo2 = IN[3]

doc = DocumentManager.Instance.CurrentDBDocument
results = []
TransactionManager.Instance.EnsureInTransaction(doc)
for i in range(0, len(elementA)):
	for j in range(0, len(elementB)):
		A = elementA[i]
		B = elementB[j]
		try:
			if Autodesk.Revit.DB.JoinGeometryUtils.IsCuttingElementInJoin(doc,A,B) :
				result = Autodesk.Revit.DB.JoinGeometryUtils.UnjoinGeometry(doc,A,B)# Neu 2 cau kien dang join voi nhau thi Unjoin
		except:
			pass
		
for i in range(0, len(elementA)):
	for j in range(0, len(elementB)):
		A = elementA[i]
		B = elementB[j]
		try:
			if geo1[i].DoesIntersect(geo2[j]):#Neu cau kien intersect voi nhau
				if not Autodesk.Revit.DB.JoinGeometryUtils.AreElementsJoined(doc,A,B): #Neu cau kien khong Join nhau thi tien hanh Join
					result = Autodesk.Revit.DB.JoinGeometryUtils.JoinGeometry(doc,A,B)
					if not Autodesk.Revit.DB.JoinGeometryUtils.IsCuttingElementInJoin(doc,A,B): #NEu thu tu Join khong dung thi swtitchJoin
						result = Autodesk.Revit.DB.JoinGeometryUtils.SwitchJoinOrder(doc,A,B)
				elif not Autodesk.Revit.DB.JoinGeometryUtils.IsCuttingElementInJoin(doc,A,B): #Neu cau kien dang join thi kiem tra de switch join
					result = Autodesk.Revit.DB.JoinGeometryUtils.SwitchJoinOrder(doc,A,B)
				results.append(result)
		except:
			pass
TransactionManager.Instance.TransactionTaskDone()
#Assign your output to the OUT variable.
OUT = results</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="80171361-c0e1-4a87-9c51-7d42229fcde5" start_index="0" end="dafeef20-fde7-4045-9f25-92f23004ae16" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="56a20d69-7614-4f28-b585-86e61f7af5d0" start_index="0" end="72b4479b-5c33-4844-8f66-06bde27cb7c8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4ea11c76-c227-42b6-934f-66e1e57ce8c8" start_index="0" end="56a20d69-7614-4f28-b585-86e61f7af5d0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d0c85c09-509c-4bf9-b1e5-d483f8dd901a" start_index="0" end="80171361-c0e1-4a87-9c51-7d42229fcde5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="72b4479b-5c33-4844-8f66-06bde27cb7c8" start_index="0" end="43245b2f-029b-429b-99c2-522325b20d14" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="72b4479b-5c33-4844-8f66-06bde27cb7c8" start_index="0" end="34c5d48e-2f22-4c4a-ba56-da7974fa28db" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dafeef20-fde7-4045-9f25-92f23004ae16" start_index="0" end="90fa7cca-7d18-4a69-b35a-e733da099a47" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dafeef20-fde7-4045-9f25-92f23004ae16" start_index="0" end="34c5d48e-2f22-4c4a-ba56-da7974fa28db" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="43245b2f-029b-429b-99c2-522325b20d14" start_index="0" end="446d8020-3c23-4dfd-9e78-92caf0a5e0c3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="90fa7cca-7d18-4a69-b35a-e733da099a47" start_index="0" end="1cbaed5e-3504-47e4-b2b3-a048871d64b7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="446d8020-3c23-4dfd-9e78-92caf0a5e0c3" start_index="0" end="34c5d48e-2f22-4c4a-ba56-da7974fa28db" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1cbaed5e-3504-47e4-b2b3-a048871d64b7" start_index="0" end="34c5d48e-2f22-4c4a-ba56-da7974fa28db" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="aca26d11-3a9a-4971-aa7f-85a8621cfcbf" annotationText="Đối tượng ***bị Cắt" left="447.553721550393" top="-69.6559748065824" width="347.374898862551" height="278.09482203781" fontSize="14" InitialTop="-39.6559748065824" InitialHeight="123" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="80171361-c0e1-4a87-9c51-7d42229fcde5" />
      <Models ModelGuid="72b4479b-5c33-4844-8f66-06bde27cb7c8" />
      <Models ModelGuid="22861bf9-3774-406b-8c15-ad7ef68c3a94" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="813b2034-172c-4a65-8ab9-d51cf1969c6e" annotationText="Đối tượng ***Cắt" left="448.5" top="252.5" width="344.959684442465" height="201.579581294848" fontSize="14" InitialTop="282.5" InitialHeight="210.5" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="56a20d69-7614-4f28-b585-86e61f7af5d0" />
      <Models ModelGuid="dafeef20-fde7-4045-9f25-92f23004ae16" />
      <Models ModelGuid="fa5f76ac-b98b-447a-9d08-489730acec61" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>