<Workspace Version="0.9.1.4062" X="96.0703604524978" Y="177.767704042725" zoom="0.143892342901823" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Wall" resolvedName="Revit.Elements.Wall" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="a485a26d-e7e8-415a-abb3-b440fbc24c0d" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Rooms" x="37" y="228" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a8e8" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a8ea" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a8eb" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a900" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a901" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a902" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a903" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a917" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a936" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a94e" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a972" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a992" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005a9ba" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005aa11" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005aa2d" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005aa6b" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005aa6c" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005aa6e" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005aa6f" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005aa71" />
      <instance id="6840eb24-53a3-40ba-bfce-2975fa3d7aa3-0005aa72" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <CoreNodeModels.Input.StringInput guid="eab6798f-4538-4106-b34a-67e3f007f763" type="CoreNodeModels.Input.StringInput" nickname="filter" x="307.056381655003" y="390.827395712912" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>Rooms</System.String>
      <System.String value="Rooms" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="54d80628-4cdc-47b8-b27d-3f358916d48a" type="PythonNodeModels.PythonNode" nickname="Python Script-Filterer" x="559.165685642931" y="254.581113160426" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
elems = IN[0]
cateName = IN[1]

res = []

for e in elems:
	ee = UnwrapElement(e)
	if ee.Category.Name == cateName:
		res.append(e)

#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9b357416-d938-4aea-9c59-e5669a6c14b6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Solids" x="775.230497084739" y="265.052644676489" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Solids" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3b105aa7-5e55-4383-a4ed-59dd8d781f6b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="968.376621596366" y="265.39111035728" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a01be665-8a9c-4ef4-8ecc-e47bb21d71c5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Explode" x="1115.40206162369" y="261.098396779839" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Explode" />
    <PythonNodeModels.PythonNode guid="8bec2740-1429-4a4f-bece-c39cad3b9812" type="PythonNodeModels.PythonNode" nickname="Python Script-Get Surface vector Z -1" x="1377.25758984754" y="245.000720864439" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

listSurfaces = IN[0]

res = []
for list in listSurfaces:
	for sf in list:
		if sf.NormalAtParameter(0.5,0.5).Z == -1:
			res.append(sf)
			

#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="663058e1-3000-46c0-82ca-b564e986f3ac" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surface.PerimeterCurves" x="1678.8207186627" y="236.415293709559" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.PerimeterCurves" />
    <DSRevitNodesUI.Levels guid="3479bd91-89d4-4291-be12-e338657f6b3b" type="DSRevitNodesUI.Levels" nickname="Levels" x="858.971710597745" y="358.734136260417" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="0:Exc LV" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="69f10347-7a94-44af-8cfb-040f625cf85f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="794.068615053958" y="503.588512779203" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="4569548a-ff95-4ce6-9b6b-674f0dd77191" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Room Param" x="310.658202665877" y="536.263200367707" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="&quot;Name&quot;;&#xA;&quot;Unbounded Height&quot;;" ShouldFocus="false" />
    <CoreNodeModels.Input.StringInput guid="91077163-b73e-4335-9454-8b52f328482e" type="CoreNodeModels.Input.StringInput" nickname="Wall type name" x="290.491114677517" y="954.211214870793" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>FW</System.String>
      <System.String value="FW" />
    </CoreNodeModels.Input.StringInput>
    <DSRevitNodesUI.Levels guid="5418fa2d-bc80-4936-81fe-bd1d87bf793b" type="DSRevitNodesUI.Levels" nickname="Levels" x="262.44479237721" y="640.169777757577" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="1:Level 1" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ced674f1-06a6-4649-a305-54f262abdbbe" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Wall param" x="282.535154919904" y="726.137004123769" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="param = &quot;Comments&quot;;&#xA;&quot;Room Bounding&quot;;&#xA;&quot;Location Line&quot;;&#xA;&quot;Width&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="54375482-2564-4e66-9f3a-6f623f6f1645" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="791.581587390216" y="624.728764025589" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ccc385bd-7c54-4e77-886f-6657755ee22a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="+" x="1091.39121004131" y="616.376535755465" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="Operators" function="+@var[]..[],var[]..[]" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="4f991993-bf80-4a1f-aeee-9ec177d3fc7b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Wall options" x="265.159918958809" y="860.470363705625" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="100;&#xA;//Wall height over Ceiling;&#xA;0;&#xA;//wall offset (for Wall Base/len);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0f9afc38-a856-4b74-b6e1-c1f3846115d2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="WallType.ByName" x="1653.52197638092" y="368.768044082504" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.WallType.ByName@string" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="043910c2-10a8-45b7-a41e-632249f2ebcb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="3140.28244338843" y="397.061701101013" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <CoreNodeModels.Input.BoolSelector guid="063f998c-0dff-4cc8-8953-1249a8de6cf6" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean Room bounding" x="244.276846191987" y="1026.72790109605" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.Boolean>False</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <PythonNodeModels.PythonNode guid="1f9203e2-53af-4728-b02c-2c822d823450" type="PythonNodeModels.PythonNode" nickname="Python Script-Wall by curve over Room height" x="2736.17159343525" y="138.777018181635" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="4">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference("RevitNodes")
from Revit.Elements import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

listlistCurve = IN[0]
listHeight = IN[1]
level = IN[2]
walltype = IN[3]

res = []

for i in range(len(listlistCurve)):
	list = []
	for c in listlistCurve[i]:
		w = Wall.ByCurveAndHeight(c, listHeight[i], level, walltype)
		list.append(w)
	res.append(list)

#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="74c5a50b-e586-4b14-b1f2-a2c6bd760025" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="3141.87321356033" y="546.733495449958" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6d763d5e-d19b-494b-aedf-83c568defc31" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Location Line" x="261.774896639315" y="1098.68065791926" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="0;&#xA;//Wall centerline;&#xA;1;&#xA;2;&#xA;3;&#xA;4;&#xA;//Core face ext;&#xA;5;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="56cca814-bf5a-4385-96d0-e6886b81d655" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1453" y="139" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="10;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ca448af7-90d9-4913-a2ce-674a7e4de83e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PolyCurve.ByJoinedCurves" x="2026.82644747109" y="-164.455852718983" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByJoinedCurves@Autodesk.DesignScript.Geometry.Curve[]" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="4c95df5d-8f78-4aa1-b219-d2ab2b87696d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2100.54634319122" y="-65.6137009279176" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="w/2+o;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8d3478eb-7ef9-46c6-b828-58cdb7241213" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Explode" x="2498.93839176035" y="-43.9868629212947" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Explode" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e57c59ad-d208-42ae-9857-c55089d3f73a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="1750.30128677655" y="1.37611992619992" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string" />
    <PythonNodeModels.PythonNode guid="f8b33d56-c340-4dfe-b8ad-dc8bf461cf43" type="PythonNodeModels.PythonNode" nickname="filter polycurves" x="2261.42176980326" y="-93.9461621416573" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

polycurve = IN[0]
distance = IN[1]
extend = False

res = []
for p in polycurve:
	newC1 = p.Offset (distance,extend)
	newC2 = p.Offset (-distance,extend)
	
	if newC1.Length &gt; newC2.Length:
		res.append(newC2)
	else:
		res.append(newC1)

#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="c076fc13-3df4-4ff9-bd66-0b30a868f065" type="PythonNodeModels.PythonNode" nickname="Python Script-Set parameter (Room Name info)" x="3141.51588497574" y="232.708632192252" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="3">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference("RevitNodes")
from Revit.Elements import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

walls = IN[0]
paramName = IN[1]
values = IN[2]

res = []

for i in range(len(walls)):
	for w in walls[i]:
		w.SetParameterByName(paramName,values[i])

#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a485a26d-e7e8-415a-abb3-b440fbc24c0d" start_index="0" end="54d80628-4cdc-47b8-b27d-3f358916d48a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eab6798f-4538-4106-b34a-67e3f007f763" start_index="0" end="54d80628-4cdc-47b8-b27d-3f358916d48a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54d80628-4cdc-47b8-b27d-3f358916d48a" start_index="0" end="9b357416-d938-4aea-9c59-e5669a6c14b6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54d80628-4cdc-47b8-b27d-3f358916d48a" start_index="0" end="69f10347-7a94-44af-8cfb-040f625cf85f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54d80628-4cdc-47b8-b27d-3f358916d48a" start_index="0" end="54375482-2564-4e66-9f3a-6f623f6f1645" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9b357416-d938-4aea-9c59-e5669a6c14b6" start_index="0" end="3b105aa7-5e55-4383-a4ed-59dd8d781f6b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3b105aa7-5e55-4383-a4ed-59dd8d781f6b" start_index="0" end="a01be665-8a9c-4ef4-8ecc-e47bb21d71c5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a01be665-8a9c-4ef4-8ecc-e47bb21d71c5" start_index="0" end="8bec2740-1429-4a4f-bece-c39cad3b9812" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8bec2740-1429-4a4f-bece-c39cad3b9812" start_index="0" end="663058e1-3000-46c0-82ca-b564e986f3ac" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="663058e1-3000-46c0-82ca-b564e986f3ac" start_index="0" end="ca448af7-90d9-4913-a2ce-674a7e4de83e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="69f10347-7a94-44af-8cfb-040f625cf85f" start_index="0" end="c076fc13-3df4-4ff9-bd66-0b30a868f065" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4569548a-ff95-4ce6-9b6b-674f0dd77191" start_index="0" end="69f10347-7a94-44af-8cfb-040f625cf85f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4569548a-ff95-4ce6-9b6b-674f0dd77191" start_index="1" end="54375482-2564-4e66-9f3a-6f623f6f1645" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="91077163-b73e-4335-9454-8b52f328482e" start_index="0" end="0f9afc38-a856-4b74-b6e1-c1f3846115d2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5418fa2d-bc80-4936-81fe-bd1d87bf793b" start_index="0" end="1f9203e2-53af-4728-b02c-2c822d823450" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ced674f1-06a6-4649-a305-54f262abdbbe" start_index="0" end="c076fc13-3df4-4ff9-bd66-0b30a868f065" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ced674f1-06a6-4649-a305-54f262abdbbe" start_index="1" end="043910c2-10a8-45b7-a41e-632249f2ebcb" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ced674f1-06a6-4649-a305-54f262abdbbe" start_index="2" end="74c5a50b-e586-4b14-b1f2-a2c6bd760025" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ced674f1-06a6-4649-a305-54f262abdbbe" start_index="3" end="e57c59ad-d208-42ae-9857-c55089d3f73a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54375482-2564-4e66-9f3a-6f623f6f1645" start_index="0" end="ccc385bd-7c54-4e77-886f-6657755ee22a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ccc385bd-7c54-4e77-886f-6657755ee22a" start_index="0" end="1f9203e2-53af-4728-b02c-2c822d823450" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4f991993-bf80-4a1f-aeee-9ec177d3fc7b" start_index="0" end="ccc385bd-7c54-4e77-886f-6657755ee22a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4f991993-bf80-4a1f-aeee-9ec177d3fc7b" start_index="1" end="4c95df5d-8f78-4aa1-b219-d2ab2b87696d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0f9afc38-a856-4b74-b6e1-c1f3846115d2" start_index="0" end="1f9203e2-53af-4728-b02c-2c822d823450" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0f9afc38-a856-4b74-b6e1-c1f3846115d2" start_index="0" end="e57c59ad-d208-42ae-9857-c55089d3f73a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="063f998c-0dff-4cc8-8953-1249a8de6cf6" start_index="0" end="043910c2-10a8-45b7-a41e-632249f2ebcb" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1f9203e2-53af-4728-b02c-2c822d823450" start_index="0" end="043910c2-10a8-45b7-a41e-632249f2ebcb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1f9203e2-53af-4728-b02c-2c822d823450" start_index="0" end="74c5a50b-e586-4b14-b1f2-a2c6bd760025" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1f9203e2-53af-4728-b02c-2c822d823450" start_index="0" end="c076fc13-3df4-4ff9-bd66-0b30a868f065" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6d763d5e-d19b-494b-aedf-83c568defc31" start_index="5" end="74c5a50b-e586-4b14-b1f2-a2c6bd760025" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ca448af7-90d9-4913-a2ce-674a7e4de83e" start_index="0" end="f8b33d56-c340-4dfe-b8ad-dc8bf461cf43" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4c95df5d-8f78-4aa1-b219-d2ab2b87696d" start_index="0" end="f8b33d56-c340-4dfe-b8ad-dc8bf461cf43" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8d3478eb-7ef9-46c6-b828-58cdb7241213" start_index="0" end="1f9203e2-53af-4728-b02c-2c822d823450" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e57c59ad-d208-42ae-9857-c55089d3f73a" start_index="0" end="4c95df5d-8f78-4aa1-b219-d2ab2b87696d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f8b33d56-c340-4dfe-b8ad-dc8bf461cf43" start_index="0" end="8d3478eb-7ef9-46c6-b828-58cdb7241213" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="f3f5edf5-d87a-4c2b-84cc-00ef3964e640" annotationText="&lt;Click here to edit the group title&gt;" left="27" top="198" width="367.056381655003" height="260.827395712912" fontSize="14" InitialTop="228" InitialHeight="260.827395712912" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="a485a26d-e7e8-415a-abb3-b440fbc24c0d" />
      <Models ModelGuid="eab6798f-4538-4106-b34a-67e3f007f763" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="c63298e0-89a7-4c04-a5c3-df446c23b762" annotationText="&lt;Click here to edit the group title&gt;" left="1740.30128677655" top="-194.455852718983" width="959.6371049838" height="314.831972645183" fontSize="14" InitialTop="-164.455852718983" InitialHeight="279.310133776806" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="ca448af7-90d9-4913-a2ce-674a7e4de83e" />
      <Models ModelGuid="4c95df5d-8f78-4aa1-b219-d2ab2b87696d" />
      <Models ModelGuid="8d3478eb-7ef9-46c6-b828-58cdb7241213" />
      <Models ModelGuid="e57c59ad-d208-42ae-9857-c55089d3f73a" />
      <Models ModelGuid="f8b33d56-c340-4dfe-b8ad-dc8bf461cf43" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-31045.1484375" eyeY="-11676.6259765625" eyeZ="18551.984375" lookX="-7435.75634765625" lookY="14625.5654296875" lookZ="-8611.17578125" upX="0.589894592761993" upY="0.430511087179184" upZ="0.683143138885498" />
  </Cameras>
</Workspace>