<Workspace Version="0.9.1.4062" X="-656.716286301481" Y="-2.19027668177836" zoom="0.671318258150714" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap>
    <ClassMap partialName="Circle" resolvedName="Autodesk.DesignScript.Geometry.Circle" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="bf93bad8-5e8f-474e-ad65-ae8aeb237809" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="32.719503994762" y="118.008476163333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9a3" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9a4" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9a5" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9a6" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9a7" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9a8" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9a9" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9aa" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9b4" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9b5" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9b6" />
      <instance id="c691228f-7bcb-4eeb-a85a-e2e6d2bf7b5e-0005c9b7" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="45e63705-e0ca-4562-bf22-371ee30fb8ee" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Revit Category Filterer 1" x="524.323254552913" y="182.098849815385" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false">
      <ID value="0a46c85c-8354-4305-9206-9341170d96bd" />
      <Name value="Revit Category Filterer 1" />
      <Description value="" />
      <Inputs>
        <Input value="" />
        <Input value="" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="defc9fec-9d91-4aac-af4e-f00d791932b6" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Filter" x="187.3880681941" y="321.862316524577" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="&quot;Walls&quot;;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="8dffbaff-0edd-4d63-9c2c-11692cc8ec7c" type="PythonNodeModels.PythonNode" nickname="Python Script-Get Wall Curve" x="806.168160917931" y="196.588614401811" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import TaskDialog
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
clr.ImportExtensions(Revit.GeometryConversion)
 
 
 
doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
walls = UnwrapElement(IN[0])

res = []

opt = Options()

for w in walls:	
	loc = w.Location
	c = loc.Curve
	res.append(c.ToProtoType())


#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="5c980276-bde5-4466-9ad6-e4a50116c00f" type="PythonNodeModels.PythonNode" nickname="Python Script-Curve loop" x="1194.75491112962" y="429.139544391094" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

 
 

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
curves = IN[0]
radius = IN[1]

def revert(c):
	
	return 0


def getCurveLoop(curves,r):
	res = []	
	i = 1
	while i &lt; len(curves):
		c0 = curves[i-1]
		circle1 = Circle.ByCenterPointRadius(c0.StartPoint,r)
		
		rest = curves[i:]		
		
		for c in rest:
			flag = circle1.DoesIntersect(c)
			if flag:
				res.append(c0)
				if 
		i+=1
	return res

res = getCurveLoop(curves,radius)
#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="64861484-bad9-4b9d-9f96-efe4b22a4ca4" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1400.81727874119" y="547.581109622678" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="c = null;&#xA;circle1 = Circle.ByCenterPointRadius(c, 50);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="29df8bc5-1557-46c2-9e4c-490dd19958eb" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="810.71814061357" y="591.070688225378" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="c = null;&#xA;curve1 = c.Reverse();" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="f83e0107-fc2d-452d-ac1e-c21b2b09f746" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get Intersected points of curves" x="1195.45238651476" y="181.57860308913" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false">
      <ID value="36deba96-ba99-4f66-9d20-715ebc36a800" />
      <Name value="Get Intersected points of curves" />
      <Description value="" />
      <Inputs>
        <Input value="curves" />
      </Inputs>
      <Outputs>
        <Output value="points" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="bf93bad8-5e8f-474e-ad65-ae8aeb237809" start_index="0" end="45e63705-e0ca-4562-bf22-371ee30fb8ee" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="45e63705-e0ca-4562-bf22-371ee30fb8ee" start_index="0" end="8dffbaff-0edd-4d63-9c2c-11692cc8ec7c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="defc9fec-9d91-4aac-af4e-f00d791932b6" start_index="0" end="45e63705-e0ca-4562-bf22-371ee30fb8ee" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8dffbaff-0edd-4d63-9c2c-11692cc8ec7c" start_index="0" end="5c980276-bde5-4466-9ad6-e4a50116c00f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8dffbaff-0edd-4d63-9c2c-11692cc8ec7c" start_index="0" end="f83e0107-fc2d-452d-ac1e-c21b2b09f746" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-48739.9140625" eyeY="29137.7109375" eyeZ="-7700.36328125" lookX="-6446.962890625" lookY="-35112.7265625" lookZ="16375.4775390625" upX="-0.284690767526627" upY="0.629320383071899" upZ="0.723123073577881" />
  </Cameras>
</Workspace>