{
  "Uuid": "aec15bf1-25f3-434f-b5ae-f64a048268d2",
  "IsCustomNode": false,
  "Description": null,
  "Name": "FW Scaffolding for Beam-210420",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "e1031f30-7a9f-413d-a449-06cde94e181b-00054764"
      ],
      "Id": "758a614ac132424a9b7ef51454c30d52",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "12d3b44a3343418b9a80c10e93ab7377",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementsSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "e1031f30-7a9f-413d-a449-06cde94e181b-00054764",
        "e1031f30-7a9f-413d-a449-06cde94e181b-00054766",
        "e1031f30-7a9f-413d-a449-06cde94e181b-00054769",
        "e1031f30-7a9f-413d-a449-06cde94e181b-0005476c"
      ],
      "Id": "2b1f015ff0e34009be534575ef263972",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "4678db869763466bb09d7a411c9fd2da",
          "Name": "Elements",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys,os,json,tempfile\r\nfrom shutil import copyfile\r\nfrom json import *\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nimport Autodesk.DesignScript.Geometry\r\nfrom Autodesk.DesignScript.Geometry import *\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\nimport Autodesk.Revit.DB.BooleanOperationsUtils as BOU\r\nimport Autodesk.Revit.DB.SolidSolidCutUtils as SSUT\r\n#clr.AddReference('RevitAPIUI')\r\n#from Autodesk.Revit.UI import TaskDialog\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\nfrom System.Collections.Generic import *\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\"\"\"\r\n## add module director\r\ndynPyDir = r\"C:\\Users\\USER\\Documents\\GitHub\\cofico\\cofico\\FROM BIM MASTER TEMP 210412\\Python\\pythonDynamo\"\r\nsys.path.append(dynPyDir)\r\nimport pyDyn\r\nfrom pyDyn import *\r\n##\r\n\"\"\"\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\n\r\n# Place your code below this line\r\nbeam = UnwrapElement(IN[0])\r\n\r\n\r\n# Assign your output to the OUT variable.\r\nOUT = beam",
      "VariableInputPorts": true,
      "Id": "332882920cf14c4c9c06de901c262b3a",
      "Inputs": [
        {
          "Id": "88e6b5adf90d45b2b91e728f0db3f225",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d6506bcdce05426ea43ac5ca4f668f06",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "90bb91d9a4254e218cca1bc0534b444e",
      "Inputs": [
        {
          "Id": "af6092842cc14b7a91edcfcd8ee01fd2",
          "Name": "",
          "Description": "Node to evaluate.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6362974ed0744622b20c0303dfba3bc7",
          "Name": "",
          "Description": "Watch contents.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualize the output of node."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys, os\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nimport Autodesk.DesignScript.Geometry\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\n\r\n# Place your code below this line\r\n#path1 = os.path.abspath(Autodesk.DesignScript.__file__)\r\n#path2 = os.path.dirname(Autodesk.DesignScript.Geometry.__file__)\r\n\r\n# Assign your output to the OUT variable.\r\nOUT = dir(Revit.Elements)#clr.References[3].Location#,dir(clr.References[3].Autodesk.DesignScript.Geometry),dir(clr)",
      "VariableInputPorts": true,
      "Id": "6908afeb477d4ab8b5be793a6d0a237d",
      "Inputs": [
        {
          "Id": "88ee51f079fb4e8292235c47e83dfe15",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b9651a4fc2d94278bf4865a417e1ff81",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    }
  ],
  "Connectors": [
    {
      "Start": "12d3b44a3343418b9a80c10e93ab7377",
      "End": "88e6b5adf90d45b2b91e728f0db3f225",
      "Id": "e8a76ed260d743abb44f0f5f18e272ad"
    },
    {
      "Start": "d6506bcdce05426ea43ac5ca4f668f06",
      "End": "af6092842cc14b7a91edcfcd8ee01fd2",
      "Id": "4a3e47d2986a4c3db69c06ab617faa12"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.1.0.7500",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Select Model Element",
        "Id": "758a614ac132424a9b7ef51454c30d52",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 127.0,
        "Y": 234.0
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Elements",
        "Id": "2b1f015ff0e34009be534575ef263972",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 9.0828632770965214,
        "Y": 486.49457705027828
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "332882920cf14c4c9c06de901c262b3a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 430.93978867634951,
        "Y": 230.44070141825017
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "90bb91d9a4254e218cca1bc0534b444e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 736.10344107546678,
        "Y": 209.9322176396702
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "6908afeb477d4ab8b5be793a6d0a237d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 409.49754590962391,
        "Y": 389.30371397163458
      }
    ],
    "Annotations": [],
    "X": -221.87872740465707,
    "Y": 82.57157915364013,
    "Zoom": 0.87323933894951822
  }
}