<Workspace Version="0.9.1.4062" X="338.319210461766" Y="37.9767438790112" zoom="0.671318258150712" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="3f84f739-eadc-4777-8113-7073b82e624d" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-128.138338071928" y="5.30875604140433" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <instance id="646cc85f-ab4f-4e04-a992-61685eec49d0-00043829" />
    </Dynamo.Nodes.DSModelElementSelection>
    <DSRevitNodesUI.Categories guid="b5abae3a-e2b3-4c6b-b1be-0293a760273e" type="DSRevitNodesUI.Categories" nickname="Categories" x="74.423291637523" y="152.841594979502" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="865:StructuralColumns" />
    <PythonNodeModels.PythonNode guid="21a7b6f2-0dda-4f91-8143-d8c11dfeec18" type="PythonNodeModels.PythonNode" nickname="Python Script" x="481.334188047206" y="29.6180371091801" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2">
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('System')
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#Preparing input from dynamo to revit
link = UnwrapElement(IN[0])
category = UnwrapElement(IN[1])
linkDoc = link.GetLinkDocument()

elements = FilteredElementCollector(linkDoc).OfCategoryId(category.Id).WhereElementIsNotElementType()

#Create a genereic list for the elements
eList = List[LinkElementId]()
for e in elements:
	eList.Add(LinkElementId(link.Id,e.Id))

#All actions that makes changes to the Revit database needs to be inside a Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

createparts = PartUtils.CreateParts(doc, eList)

TransactionManager.Instance.TransactionTaskDone()

OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="dd0393a7-17e2-40ce-b1d6-3fc32efe0db9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="618.933105682715" y="251.574902482241" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2">
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('System')
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#Preparing input from dynamo to revit
link = UnwrapElement(IN[0])
category = UnwrapElement(IN[1])
linkDoc = link.GetLinkDocument()

elements = FilteredElementCollector(linkDoc).OfCategoryId(category.Id).WhereElementIsNotElementType()

#Create a genereic list for the elements
eList = List[LinkElementId]()
for e in elements:
	eList.Add(LinkElementId(link.Id,e.Id))

#All actions that makes changes to the Revit database needs to be inside a Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

createparts = PartUtils.CreateParts(doc, eList)

TransactionManager.Instance.TransactionTaskDone()

OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="684a5a33-2915-44f9-b10f-61d442c2de7f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="629.103803684547" y="452.232310653437" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2">
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('System')
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#Preparing input from dynamo to revit
link = UnwrapElement(IN[0])
category = UnwrapElement(IN[1])
linkDoc = link.GetLinkDocument()

elements = FilteredElementCollector(linkDoc).OfCategoryId(category.Id).WhereElementIsNotElementType()

#Create a genereic list for the elements
eList = List[LinkElementId]()
for e in elements:
	eList.Add(LinkElementId(link.Id,e.Id))

#All actions that makes changes to the Revit database needs to be inside a Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

createparts = PartUtils.CreateParts(doc, eList)

TransactionManager.Instance.TransactionTaskDone()

OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.Categories guid="96c9c5b7-0a34-4d35-af11-83dd2973228f" type="DSRevitNodesUI.Categories" nickname="Categories" x="71.3843891667944" y="291.150777799048" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="872:StructuralFraming" />
    <DSRevitNodesUI.Categories guid="0ec8328b-9658-4e32-8f5f-d01a4d77166f" type="DSRevitNodesUI.Categories" nickname="Categories" x="62.3811472942336" y="424.112931092088" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="344:Floors" />
    <PythonNodeModels.PythonNode guid="afb11272-c31a-40ce-ae80-2c658cfa923a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="502.673638101685" y="627.434219296923" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="2">
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('System')
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#Preparing input from dynamo to revit
link = UnwrapElement(IN[0])
category = UnwrapElement(IN[1])
linkDoc = link.GetLinkDocument()

elements = FilteredElementCollector(linkDoc).OfCategoryId(category.Id).WhereElementIsNotElementType()

#Create a genereic list for the elements
eList = List[LinkElementId]()
for e in elements:
	eList.Add(LinkElementId(link.Id,e.Id))

#All actions that makes changes to the Revit database needs to be inside a Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

createparts = PartUtils.CreateParts(doc, eList)

TransactionManager.Instance.TransactionTaskDone()

OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.Categories guid="772247a0-3fcb-4dd3-a1f7-52eda4bd971e" type="DSRevitNodesUI.Categories" nickname="Categories" x="55.1194968361909" y="596.335626857454" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="870:StructuralFoundation" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3f84f739-eadc-4777-8113-7073b82e624d" start_index="0" end="21a7b6f2-0dda-4f91-8143-d8c11dfeec18" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3f84f739-eadc-4777-8113-7073b82e624d" start_index="0" end="dd0393a7-17e2-40ce-b1d6-3fc32efe0db9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3f84f739-eadc-4777-8113-7073b82e624d" start_index="0" end="684a5a33-2915-44f9-b10f-61d442c2de7f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3f84f739-eadc-4777-8113-7073b82e624d" start_index="0" end="afb11272-c31a-40ce-ae80-2c658cfa923a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b5abae3a-e2b3-4c6b-b1be-0293a760273e" start_index="0" end="21a7b6f2-0dda-4f91-8143-d8c11dfeec18" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96c9c5b7-0a34-4d35-af11-83dd2973228f" start_index="0" end="dd0393a7-17e2-40ce-b1d6-3fc32efe0db9" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ec8328b-9658-4e32-8f5f-d01a4d77166f" start_index="0" end="684a5a33-2915-44f9-b10f-61d442c2de7f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="772247a0-3fcb-4dd3-a1f7-52eda4bd971e" start_index="0" end="afb11272-c31a-40ce-ae80-2c658cfa923a" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>