<Workspace Version="0.9.1.4062" X="-619.522898173094" Y="-416.727534816833" zoom="1.13810346721664" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f5090d4d-d4c6-4cd5-b303-5af398a99500" type="PythonNodeModels.PythonNode" nickname="Get Link Instances" x="644.120894022092" y="530.064646927407" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
import Autodesk
import sys
import clr
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager


rvt = IN[0]
link=[]
name=[]
linkinst=[]

doc = DocumentManager.Instance.CurrentDBDocument

			
#looks for links in the active project, add instances to a list
collector = FilteredElementCollector(doc)
filter = ElementCategoryFilter(BuiltInCategory.OST_RvtLinks)
linkinst.append(collector.WherePasses(filter).WhereElementIsNotElementType().ToElements())
	
OUT = (linkinst)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7561ac8a-92c2-40c0-89e1-32e5e6f50976" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1189.98658082337" y="492.518606227694" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f3ef89dc-66ec-4329-9680-873c7f8dc51a" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="850.307069720983" y="498.54312029502" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" CodeText="linkInstances;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="08a2eac8-64ce-4bb6-b1b0-67cfa040d9c3" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="DeleteRevitInstances" x="1464.10397124431" y="495.618561848174" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false">
      <ID value="e7e0334b-51b5-4bca-b06c-95475bb7dd49" />
      <Name value="DeleteRevitInstances" />
      <Description value="Delete Revit Instances" />
      <Inputs>
        <Input value="Instances" />
        <Input value="TrueOrFalse" />
      </Inputs>
      <Outputs>
        <Output value="OUT" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <CoreNodeModels.Input.BoolSelector guid="f92d5070-9ef0-4dea-be55-33fc1acca915" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="647.233377350296" y="637.458198568878" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f5090d4d-d4c6-4cd5-b303-5af398a99500" start_index="0" end="f3ef89dc-66ec-4329-9680-873c7f8dc51a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7561ac8a-92c2-40c0-89e1-32e5e6f50976" start_index="0" end="08a2eac8-64ce-4bb6-b1b0-67cfa040d9c3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f3ef89dc-66ec-4329-9680-873c7f8dc51a" start_index="0" end="7561ac8a-92c2-40c0-89e1-32e5e6f50976" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f92d5070-9ef0-4dea-be55-33fc1acca915" start_index="0" end="08a2eac8-64ce-4bb6-b1b0-67cfa040d9c3" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>