<Workspace Version="0.9.1.4062" X="-349.557156780506" Y="-9.98949931934695" zoom="0.977220601341529" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="77a3cc99-6465-4329-a5fb-477ad24639b3" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="275" y="179.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <instance id="76a62ce6-a980-4d83-a15f-84101f1fc5b8-00051991" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="896e2a02-8640-45ff-9edd-1f7a7a50ad93" type="PythonNodeModels.PythonNode" nickname="Python Script" x="605.379211172809" y="149.924644880638" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
clr.AddReference('RevitServices')
from RevitServices.Transactions import TransactionManager
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

walls = UnwrapElement(IN[0])
#####################################################
walltypes=[]#WallType
wallthicks=[]#double
wallsPinned=[]#bool
wallsIsStacked=[]#bool
wallsFlipped=[]#bool
wallLevelIds=[]#Id
wallLocations=[]#LocationCurve

compoundStrucs=[]
compoundStrucLayers=[]
compoundStrucLayerMaterialIds=[]
compoundStrucLayerMaterials=[]
materialFunctionAssigns=[]
materialFunctionWidths=[]
wallCurves=[]
wallEndpoints=[]

for wall in walls:
	walltypes.append(wall.WallType)
	wallthicks.append(wall.Width*304.8)# feet to mm
	wallsPinned.append(wall.Pinned)
	wallsIsStacked.append(wall.IsStackedWall)
	wallsFlipped.append(wall.Flipped)
	wallLevelIds.append(wall.LevelId)
	wallLocations.append(wall.Location)
	
for wallLocation in wallLocations:
	wallCurves.append(wallLocation.Curve)
	endpoints=[]
	endpoints.append(wallLocation.Curve.GetEndPoint(0))
	endpoints.append(wallLocation.Curve.GetEndPoint(1))
	wallEndpoints.append(endpoints)	
	

for walltype in walltypes:
	compoundStrucs.append(walltype.GetCompoundStructure())
for compoundStruc in compoundStrucs:
	compoundStrucLayers.append(compoundStruc.GetLayers())
	
for compoundStrucLayer in compoundStrucLayers:
	matFuncAssign=[]
	matFuncWidth=[]
	matIds=[]
	mats=[]
	for layer in compoundStrucLayer:		
		matFuncAssign.append(layer.Function)
		matFuncWidth.append(layer.Width*304.8)
		matIds.append(layer.MaterialId)
		matelem = doc.GetElement(layer.MaterialId)
		mats.append(matelem.Name) #################### Cần xét tới khả năng &lt;By Category&gt; của vật liệu
	materialFunctionAssigns.append(matFuncAssign)
	materialFunctionWidths.append(matFuncWidth)
	compoundStrucLayerMaterialIds.append(matIds)
	compoundStrucLayerMaterials.append(mats)
# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)



# End Transaction
TransactionManager.Instance.TransactionTaskDone()
doc.Regenerate()

#Assign your output to the OUT variable.
OUT = compoundStrucLayers,compoundStrucLayerMaterialIds,compoundStrucLayerMaterials
#wallCurves, wallEndpoints
#compoundStrucs,compoundStrucLayers,materialFunctionAssigns, materialFunctionWidths
#walltypes,wallthicks,wallsPinned,wallsIsStacked,wallsFlipped,wallLevelIds,wallLocations</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="70746729-4144-4fc8-a6c7-23e3e28cb080" type="CoreNodeModels.Watch" nickname="Watch" x="835.017903004328" y="62.6043261319066" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
    <PythonNodeModels.PythonNode guid="29176865-2833-491c-9a52-fdf5b42350fb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="602.02251422811" y="307.048237870844" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
clr.AddReference('RevitServices')
from RevitServices.Transactions import TransactionManager
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

wall = UnwrapElement(IN[0])
#####################################################
geo = wall.get_Geometry(Autodesk.Revit.DB.Options)




# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)
# End Transaction
TransactionManager.Instance.TransactionTaskDone()
doc.Regenerate()

#Assign your output to the OUT variable.
OUT = geo</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="77a3cc99-6465-4329-a5fb-477ad24639b3" start_index="0" end="896e2a02-8640-45ff-9edd-1f7a7a50ad93" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="77a3cc99-6465-4329-a5fb-477ad24639b3" start_index="0" end="29176865-2833-491c-9a52-fdf5b42350fb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="896e2a02-8640-45ff-9edd-1f7a7a50ad93" start_index="0" end="70746729-4144-4fc8-a6c7-23e3e28cb080" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-39.476202427171" eyeY="42.7658859627686" eyeZ="190.80164506466" lookX="39.476202427171" lookY="-42.7658859627686" lookZ="-190.80164506466" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>